// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PClipboardReadRequest.proto

#include "PClipboardReadRequest.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace protobuf {
namespace mozilla {
namespace PClipboardReadRequest {
PROTOBUF_CONSTEXPR Msg_GetData::Msg_GetData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.a_aflavors_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Msg_GetDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Msg_GetDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Msg_GetDataDefaultTypeInternal() {}
  union {
    Msg_GetData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Msg_GetDataDefaultTypeInternal _Msg_GetData_default_instance_;
PROTOBUF_CONSTEXPR Reply_GetData::Reply_GetData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.a_atransferabledata_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Reply_GetDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Reply_GetDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Reply_GetDataDefaultTypeInternal() {}
  union {
    Reply_GetData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Reply_GetDataDefaultTypeInternal _Reply_GetData_default_instance_;
PROTOBUF_CONSTEXPR Msg_GetDataSync::Msg_GetDataSync(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.a_aflavors_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Msg_GetDataSyncDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Msg_GetDataSyncDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Msg_GetDataSyncDefaultTypeInternal() {}
  union {
    Msg_GetDataSync _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Msg_GetDataSyncDefaultTypeInternal _Msg_GetDataSync_default_instance_;
PROTOBUF_CONSTEXPR Reply_GetDataSync::Reply_GetDataSync(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.a_atransferabledata_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Reply_GetDataSyncDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Reply_GetDataSyncDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Reply_GetDataSyncDefaultTypeInternal() {}
  union {
    Reply_GetDataSync _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Reply_GetDataSyncDefaultTypeInternal _Reply_GetDataSync_default_instance_;
PROTOBUF_CONSTEXPR Msg___delete__::Msg___delete__(
    ::_pbi::ConstantInitialized) {}
struct Msg___delete__DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Msg___delete__DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Msg___delete__DefaultTypeInternal() {}
  union {
    Msg___delete__ _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Msg___delete__DefaultTypeInternal _Msg___delete___default_instance_;
PROTOBUF_CONSTEXPR Reply___delete__::Reply___delete__(
    ::_pbi::ConstantInitialized) {}
struct Reply___delete__DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Reply___delete__DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Reply___delete__DefaultTypeInternal() {}
  union {
    Reply___delete__ _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Reply___delete__DefaultTypeInternal _Reply___delete___default_instance_;
}  // namespace PClipboardReadRequest
}  // namespace mozilla
}  // namespace protobuf
static ::_pb::Metadata file_level_metadata_PClipboardReadRequest_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_PClipboardReadRequest_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_PClipboardReadRequest_2eproto = nullptr;

const uint32_t TableStruct_PClipboardReadRequest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::PClipboardReadRequest::Msg_GetData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::PClipboardReadRequest::Msg_GetData, _impl_.a_aflavors_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::PClipboardReadRequest::Reply_GetData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::PClipboardReadRequest::Reply_GetData, _impl_.a_atransferabledata_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::PClipboardReadRequest::Msg_GetDataSync, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::PClipboardReadRequest::Msg_GetDataSync, _impl_.a_aflavors_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::PClipboardReadRequest::Reply_GetDataSync, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::PClipboardReadRequest::Reply_GetDataSync, _impl_.a_atransferabledata_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::PClipboardReadRequest::Msg___delete__, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::PClipboardReadRequest::Reply___delete__, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::protobuf::mozilla::PClipboardReadRequest::Msg_GetData)},
  { 7, -1, -1, sizeof(::protobuf::mozilla::PClipboardReadRequest::Reply_GetData)},
  { 14, -1, -1, sizeof(::protobuf::mozilla::PClipboardReadRequest::Msg_GetDataSync)},
  { 21, -1, -1, sizeof(::protobuf::mozilla::PClipboardReadRequest::Reply_GetDataSync)},
  { 28, -1, -1, sizeof(::protobuf::mozilla::PClipboardReadRequest::Msg___delete__)},
  { 34, -1, -1, sizeof(::protobuf::mozilla::PClipboardReadRequest::Reply___delete__)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::protobuf::mozilla::PClipboardReadRequest::_Msg_GetData_default_instance_._instance,
  &::protobuf::mozilla::PClipboardReadRequest::_Reply_GetData_default_instance_._instance,
  &::protobuf::mozilla::PClipboardReadRequest::_Msg_GetDataSync_default_instance_._instance,
  &::protobuf::mozilla::PClipboardReadRequest::_Reply_GetDataSync_default_instance_._instance,
  &::protobuf::mozilla::PClipboardReadRequest::_Msg___delete___default_instance_._instance,
  &::protobuf::mozilla::PClipboardReadRequest::_Reply___delete___default_instance_._instance,
};

const char descriptor_table_protodef_PClipboardReadRequest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033PClipboardReadRequest.proto\022&protobuf."
  "mozilla.PClipboardReadRequest\032\016DOMTypes."
  "proto\032\025IPCTransferable.proto\032\030NeckoChann"
  "elParams.proto\"!\n\013Msg_GetData\022\022\n\na_aFlav"
  "ors\030\001 \003(\t\"^\n\rReply_GetData\022M\n\023a_aTransfe"
  "rableData\030\001 \001(\01320.protobuf.mozilla.dom.I"
  "PCTransferableDataOrError\"%\n\017Msg_GetData"
  "Sync\022\022\n\na_aFlavors\030\001 \003(\t\"b\n\021Reply_GetDat"
  "aSync\022M\n\023a_aTransferableData\030\001 \001(\01320.pro"
  "tobuf.mozilla.dom.IPCTransferableDataOrE"
  "rror\"\020\n\016Msg___delete__\"\022\n\020Reply___delete"
  "__b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_PClipboardReadRequest_2eproto_deps[3] = {
  &::descriptor_table_DOMTypes_2eproto,
  &::descriptor_table_IPCTransferable_2eproto,
  &::descriptor_table_NeckoChannelParams_2eproto,
};
static ::_pbi::once_flag descriptor_table_PClipboardReadRequest_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_PClipboardReadRequest_2eproto = {
    false, false, 450, descriptor_table_protodef_PClipboardReadRequest_2eproto,
    "PClipboardReadRequest.proto",
    &descriptor_table_PClipboardReadRequest_2eproto_once, descriptor_table_PClipboardReadRequest_2eproto_deps, 3, 6,
    schemas, file_default_instances, TableStruct_PClipboardReadRequest_2eproto::offsets,
    file_level_metadata_PClipboardReadRequest_2eproto, file_level_enum_descriptors_PClipboardReadRequest_2eproto,
    file_level_service_descriptors_PClipboardReadRequest_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_PClipboardReadRequest_2eproto_getter() {
  return &descriptor_table_PClipboardReadRequest_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_PClipboardReadRequest_2eproto(&descriptor_table_PClipboardReadRequest_2eproto);
namespace protobuf {
namespace mozilla {
namespace PClipboardReadRequest {

// ===================================================================

class Msg_GetData::_Internal {
 public:
};

Msg_GetData::Msg_GetData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla.PClipboardReadRequest.Msg_GetData)
}
Msg_GetData::Msg_GetData(const Msg_GetData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Msg_GetData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.a_aflavors_){from._impl_.a_aflavors_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla.PClipboardReadRequest.Msg_GetData)
}

inline void Msg_GetData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.a_aflavors_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Msg_GetData::~Msg_GetData() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla.PClipboardReadRequest.Msg_GetData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Msg_GetData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.a_aflavors_.~RepeatedPtrField();
}

void Msg_GetData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Msg_GetData::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla.PClipboardReadRequest.Msg_GetData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.a_aflavors_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Msg_GetData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string a_aFlavors = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_a_aflavors();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "protobuf.mozilla.PClipboardReadRequest.Msg_GetData.a_aFlavors"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Msg_GetData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla.PClipboardReadRequest.Msg_GetData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string a_aFlavors = 1;
  for (int i = 0, n = this->_internal_a_aflavors_size(); i < n; i++) {
    const auto& s = this->_internal_a_aflavors(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.mozilla.PClipboardReadRequest.Msg_GetData.a_aFlavors");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla.PClipboardReadRequest.Msg_GetData)
  return target;
}

size_t Msg_GetData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla.PClipboardReadRequest.Msg_GetData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string a_aFlavors = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.a_aflavors_.size());
  for (int i = 0, n = _impl_.a_aflavors_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.a_aflavors_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Msg_GetData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Msg_GetData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Msg_GetData::GetClassData() const { return &_class_data_; }


void Msg_GetData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Msg_GetData*>(&to_msg);
  auto& from = static_cast<const Msg_GetData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla.PClipboardReadRequest.Msg_GetData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.a_aflavors_.MergeFrom(from._impl_.a_aflavors_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Msg_GetData::CopyFrom(const Msg_GetData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla.PClipboardReadRequest.Msg_GetData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_GetData::IsInitialized() const {
  return true;
}

void Msg_GetData::InternalSwap(Msg_GetData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.a_aflavors_.InternalSwap(&other->_impl_.a_aflavors_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Msg_GetData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PClipboardReadRequest_2eproto_getter, &descriptor_table_PClipboardReadRequest_2eproto_once,
      file_level_metadata_PClipboardReadRequest_2eproto[0]);
}

// ===================================================================

class Reply_GetData::_Internal {
 public:
  static const ::protobuf::mozilla::dom::IPCTransferableDataOrError& a_atransferabledata(const Reply_GetData* msg);
};

const ::protobuf::mozilla::dom::IPCTransferableDataOrError&
Reply_GetData::_Internal::a_atransferabledata(const Reply_GetData* msg) {
  return *msg->_impl_.a_atransferabledata_;
}
void Reply_GetData::clear_a_atransferabledata() {
  if (GetArenaForAllocation() == nullptr && _impl_.a_atransferabledata_ != nullptr) {
    delete _impl_.a_atransferabledata_;
  }
  _impl_.a_atransferabledata_ = nullptr;
}
Reply_GetData::Reply_GetData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla.PClipboardReadRequest.Reply_GetData)
}
Reply_GetData::Reply_GetData(const Reply_GetData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Reply_GetData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.a_atransferabledata_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_a_atransferabledata()) {
    _this->_impl_.a_atransferabledata_ = new ::protobuf::mozilla::dom::IPCTransferableDataOrError(*from._impl_.a_atransferabledata_);
  }
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla.PClipboardReadRequest.Reply_GetData)
}

inline void Reply_GetData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.a_atransferabledata_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Reply_GetData::~Reply_GetData() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla.PClipboardReadRequest.Reply_GetData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Reply_GetData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.a_atransferabledata_;
}

void Reply_GetData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Reply_GetData::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla.PClipboardReadRequest.Reply_GetData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.a_atransferabledata_ != nullptr) {
    delete _impl_.a_atransferabledata_;
  }
  _impl_.a_atransferabledata_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Reply_GetData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .protobuf.mozilla.dom.IPCTransferableDataOrError a_aTransferableData = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_a_atransferabledata(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Reply_GetData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla.PClipboardReadRequest.Reply_GetData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .protobuf.mozilla.dom.IPCTransferableDataOrError a_aTransferableData = 1;
  if (this->_internal_has_a_atransferabledata()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::a_atransferabledata(this),
        _Internal::a_atransferabledata(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla.PClipboardReadRequest.Reply_GetData)
  return target;
}

size_t Reply_GetData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla.PClipboardReadRequest.Reply_GetData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .protobuf.mozilla.dom.IPCTransferableDataOrError a_aTransferableData = 1;
  if (this->_internal_has_a_atransferabledata()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.a_atransferabledata_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Reply_GetData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Reply_GetData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Reply_GetData::GetClassData() const { return &_class_data_; }


void Reply_GetData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Reply_GetData*>(&to_msg);
  auto& from = static_cast<const Reply_GetData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla.PClipboardReadRequest.Reply_GetData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_a_atransferabledata()) {
    _this->_internal_mutable_a_atransferabledata()->::protobuf::mozilla::dom::IPCTransferableDataOrError::MergeFrom(
        from._internal_a_atransferabledata());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Reply_GetData::CopyFrom(const Reply_GetData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla.PClipboardReadRequest.Reply_GetData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Reply_GetData::IsInitialized() const {
  return true;
}

void Reply_GetData::InternalSwap(Reply_GetData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.a_atransferabledata_, other->_impl_.a_atransferabledata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Reply_GetData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PClipboardReadRequest_2eproto_getter, &descriptor_table_PClipboardReadRequest_2eproto_once,
      file_level_metadata_PClipboardReadRequest_2eproto[1]);
}

// ===================================================================

class Msg_GetDataSync::_Internal {
 public:
};

Msg_GetDataSync::Msg_GetDataSync(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla.PClipboardReadRequest.Msg_GetDataSync)
}
Msg_GetDataSync::Msg_GetDataSync(const Msg_GetDataSync& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Msg_GetDataSync* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.a_aflavors_){from._impl_.a_aflavors_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla.PClipboardReadRequest.Msg_GetDataSync)
}

inline void Msg_GetDataSync::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.a_aflavors_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Msg_GetDataSync::~Msg_GetDataSync() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla.PClipboardReadRequest.Msg_GetDataSync)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Msg_GetDataSync::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.a_aflavors_.~RepeatedPtrField();
}

void Msg_GetDataSync::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Msg_GetDataSync::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla.PClipboardReadRequest.Msg_GetDataSync)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.a_aflavors_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Msg_GetDataSync::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string a_aFlavors = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_a_aflavors();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "protobuf.mozilla.PClipboardReadRequest.Msg_GetDataSync.a_aFlavors"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Msg_GetDataSync::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla.PClipboardReadRequest.Msg_GetDataSync)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string a_aFlavors = 1;
  for (int i = 0, n = this->_internal_a_aflavors_size(); i < n; i++) {
    const auto& s = this->_internal_a_aflavors(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.mozilla.PClipboardReadRequest.Msg_GetDataSync.a_aFlavors");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla.PClipboardReadRequest.Msg_GetDataSync)
  return target;
}

size_t Msg_GetDataSync::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla.PClipboardReadRequest.Msg_GetDataSync)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string a_aFlavors = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.a_aflavors_.size());
  for (int i = 0, n = _impl_.a_aflavors_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.a_aflavors_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Msg_GetDataSync::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Msg_GetDataSync::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Msg_GetDataSync::GetClassData() const { return &_class_data_; }


void Msg_GetDataSync::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Msg_GetDataSync*>(&to_msg);
  auto& from = static_cast<const Msg_GetDataSync&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla.PClipboardReadRequest.Msg_GetDataSync)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.a_aflavors_.MergeFrom(from._impl_.a_aflavors_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Msg_GetDataSync::CopyFrom(const Msg_GetDataSync& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla.PClipboardReadRequest.Msg_GetDataSync)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_GetDataSync::IsInitialized() const {
  return true;
}

void Msg_GetDataSync::InternalSwap(Msg_GetDataSync* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.a_aflavors_.InternalSwap(&other->_impl_.a_aflavors_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Msg_GetDataSync::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PClipboardReadRequest_2eproto_getter, &descriptor_table_PClipboardReadRequest_2eproto_once,
      file_level_metadata_PClipboardReadRequest_2eproto[2]);
}

// ===================================================================

class Reply_GetDataSync::_Internal {
 public:
  static const ::protobuf::mozilla::dom::IPCTransferableDataOrError& a_atransferabledata(const Reply_GetDataSync* msg);
};

const ::protobuf::mozilla::dom::IPCTransferableDataOrError&
Reply_GetDataSync::_Internal::a_atransferabledata(const Reply_GetDataSync* msg) {
  return *msg->_impl_.a_atransferabledata_;
}
void Reply_GetDataSync::clear_a_atransferabledata() {
  if (GetArenaForAllocation() == nullptr && _impl_.a_atransferabledata_ != nullptr) {
    delete _impl_.a_atransferabledata_;
  }
  _impl_.a_atransferabledata_ = nullptr;
}
Reply_GetDataSync::Reply_GetDataSync(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla.PClipboardReadRequest.Reply_GetDataSync)
}
Reply_GetDataSync::Reply_GetDataSync(const Reply_GetDataSync& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Reply_GetDataSync* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.a_atransferabledata_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_a_atransferabledata()) {
    _this->_impl_.a_atransferabledata_ = new ::protobuf::mozilla::dom::IPCTransferableDataOrError(*from._impl_.a_atransferabledata_);
  }
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla.PClipboardReadRequest.Reply_GetDataSync)
}

inline void Reply_GetDataSync::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.a_atransferabledata_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Reply_GetDataSync::~Reply_GetDataSync() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla.PClipboardReadRequest.Reply_GetDataSync)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Reply_GetDataSync::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.a_atransferabledata_;
}

void Reply_GetDataSync::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Reply_GetDataSync::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla.PClipboardReadRequest.Reply_GetDataSync)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.a_atransferabledata_ != nullptr) {
    delete _impl_.a_atransferabledata_;
  }
  _impl_.a_atransferabledata_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Reply_GetDataSync::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .protobuf.mozilla.dom.IPCTransferableDataOrError a_aTransferableData = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_a_atransferabledata(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Reply_GetDataSync::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla.PClipboardReadRequest.Reply_GetDataSync)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .protobuf.mozilla.dom.IPCTransferableDataOrError a_aTransferableData = 1;
  if (this->_internal_has_a_atransferabledata()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::a_atransferabledata(this),
        _Internal::a_atransferabledata(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla.PClipboardReadRequest.Reply_GetDataSync)
  return target;
}

size_t Reply_GetDataSync::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla.PClipboardReadRequest.Reply_GetDataSync)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .protobuf.mozilla.dom.IPCTransferableDataOrError a_aTransferableData = 1;
  if (this->_internal_has_a_atransferabledata()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.a_atransferabledata_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Reply_GetDataSync::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Reply_GetDataSync::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Reply_GetDataSync::GetClassData() const { return &_class_data_; }


void Reply_GetDataSync::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Reply_GetDataSync*>(&to_msg);
  auto& from = static_cast<const Reply_GetDataSync&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla.PClipboardReadRequest.Reply_GetDataSync)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_a_atransferabledata()) {
    _this->_internal_mutable_a_atransferabledata()->::protobuf::mozilla::dom::IPCTransferableDataOrError::MergeFrom(
        from._internal_a_atransferabledata());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Reply_GetDataSync::CopyFrom(const Reply_GetDataSync& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla.PClipboardReadRequest.Reply_GetDataSync)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Reply_GetDataSync::IsInitialized() const {
  return true;
}

void Reply_GetDataSync::InternalSwap(Reply_GetDataSync* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.a_atransferabledata_, other->_impl_.a_atransferabledata_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Reply_GetDataSync::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PClipboardReadRequest_2eproto_getter, &descriptor_table_PClipboardReadRequest_2eproto_once,
      file_level_metadata_PClipboardReadRequest_2eproto[3]);
}

// ===================================================================

class Msg___delete__::_Internal {
 public:
};

Msg___delete__::Msg___delete__(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla.PClipboardReadRequest.Msg___delete__)
}
Msg___delete__::Msg___delete__(const Msg___delete__& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  Msg___delete__* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla.PClipboardReadRequest.Msg___delete__)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Msg___delete__::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Msg___delete__::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Msg___delete__::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PClipboardReadRequest_2eproto_getter, &descriptor_table_PClipboardReadRequest_2eproto_once,
      file_level_metadata_PClipboardReadRequest_2eproto[4]);
}

// ===================================================================

class Reply___delete__::_Internal {
 public:
};

Reply___delete__::Reply___delete__(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla.PClipboardReadRequest.Reply___delete__)
}
Reply___delete__::Reply___delete__(const Reply___delete__& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  Reply___delete__* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla.PClipboardReadRequest.Reply___delete__)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Reply___delete__::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Reply___delete__::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Reply___delete__::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PClipboardReadRequest_2eproto_getter, &descriptor_table_PClipboardReadRequest_2eproto_once,
      file_level_metadata_PClipboardReadRequest_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace PClipboardReadRequest
}  // namespace mozilla
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::PClipboardReadRequest::Msg_GetData*
Arena::CreateMaybeMessage< ::protobuf::mozilla::PClipboardReadRequest::Msg_GetData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::PClipboardReadRequest::Msg_GetData >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::PClipboardReadRequest::Reply_GetData*
Arena::CreateMaybeMessage< ::protobuf::mozilla::PClipboardReadRequest::Reply_GetData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::PClipboardReadRequest::Reply_GetData >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::PClipboardReadRequest::Msg_GetDataSync*
Arena::CreateMaybeMessage< ::protobuf::mozilla::PClipboardReadRequest::Msg_GetDataSync >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::PClipboardReadRequest::Msg_GetDataSync >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::PClipboardReadRequest::Reply_GetDataSync*
Arena::CreateMaybeMessage< ::protobuf::mozilla::PClipboardReadRequest::Reply_GetDataSync >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::PClipboardReadRequest::Reply_GetDataSync >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::PClipboardReadRequest::Msg___delete__*
Arena::CreateMaybeMessage< ::protobuf::mozilla::PClipboardReadRequest::Msg___delete__ >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::PClipboardReadRequest::Msg___delete__ >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::PClipboardReadRequest::Reply___delete__*
Arena::CreateMaybeMessage< ::protobuf::mozilla::PClipboardReadRequest::Reply___delete__ >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::PClipboardReadRequest::Reply___delete__ >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
