// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PCompositorBridge_protobuf.mozilla.layers.h.proto

#include "PCompositorBridge_protobuf.mozilla.layers.h.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace protobuf {
namespace mozilla {
namespace layers {
PROTOBUF_CONSTEXPR FrameStats::FrameStats(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.a_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.a_compositestart_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.a_renderstart_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.a_compositeend_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.a_transactionstart_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.a_refreshstart_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.a_fwdtime_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.a_scenebuilttime_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.a_url_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.a_resourceuploadtime_)*/0
  , /*decltype(_impl_.a_gpucacheuploadtime_)*/0
  , /*decltype(_impl_.a_contentframetime_)*/0
  , /*decltype(_impl_.a_skippedcomposites_)*/0u} {}
struct FrameStatsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FrameStatsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FrameStatsDefaultTypeInternal() {}
  union {
    FrameStats _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FrameStatsDefaultTypeInternal _FrameStats_default_instance_;
}  // namespace layers
}  // namespace mozilla
}  // namespace protobuf
namespace protobuf {
namespace mozilla {
namespace layers {

// ===================================================================

class FrameStats::_Internal {
 public:
  using HasBits = decltype(std::declval<FrameStats>()._impl_._has_bits_);
  static void set_has_a_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_a_compositestart(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_a_renderstart(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_a_compositeend(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_a_contentframetime(HasBits* has_bits) {
    (*has_bits)[0] |= 2048u;
  }
  static void set_has_a_resourceuploadtime(HasBits* has_bits) {
    (*has_bits)[0] |= 512u;
  }
  static void set_has_a_gpucacheuploadtime(HasBits* has_bits) {
    (*has_bits)[0] |= 1024u;
  }
  static void set_has_a_transactionstart(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_a_refreshstart(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_a_fwdtime(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_a_scenebuilttime(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_a_skippedcomposites(HasBits* has_bits) {
    (*has_bits)[0] |= 4096u;
  }
  static void set_has_a_url(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x000000ff) ^ 0x000000ff) != 0;
  }
};

FrameStats::FrameStats(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla.layers.FrameStats)
}
FrameStats::FrameStats(const FrameStats& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  FrameStats* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.a_id_){}
    , decltype(_impl_.a_compositestart_){}
    , decltype(_impl_.a_renderstart_){}
    , decltype(_impl_.a_compositeend_){}
    , decltype(_impl_.a_transactionstart_){}
    , decltype(_impl_.a_refreshstart_){}
    , decltype(_impl_.a_fwdtime_){}
    , decltype(_impl_.a_scenebuilttime_){}
    , decltype(_impl_.a_url_){}
    , decltype(_impl_.a_resourceuploadtime_){}
    , decltype(_impl_.a_gpucacheuploadtime_){}
    , decltype(_impl_.a_contentframetime_){}
    , decltype(_impl_.a_skippedcomposites_){}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _impl_.a_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_a_id()) {
    _this->_impl_.a_id_.Set(from._internal_a_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.a_compositestart_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_compositestart_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_a_compositestart()) {
    _this->_impl_.a_compositestart_.Set(from._internal_a_compositestart(), 
      _this->GetArenaForAllocation());
  }
  _impl_.a_renderstart_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_renderstart_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_a_renderstart()) {
    _this->_impl_.a_renderstart_.Set(from._internal_a_renderstart(), 
      _this->GetArenaForAllocation());
  }
  _impl_.a_compositeend_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_compositeend_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_a_compositeend()) {
    _this->_impl_.a_compositeend_.Set(from._internal_a_compositeend(), 
      _this->GetArenaForAllocation());
  }
  _impl_.a_transactionstart_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_transactionstart_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_a_transactionstart()) {
    _this->_impl_.a_transactionstart_.Set(from._internal_a_transactionstart(), 
      _this->GetArenaForAllocation());
  }
  _impl_.a_refreshstart_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_refreshstart_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_a_refreshstart()) {
    _this->_impl_.a_refreshstart_.Set(from._internal_a_refreshstart(), 
      _this->GetArenaForAllocation());
  }
  _impl_.a_fwdtime_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_fwdtime_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_a_fwdtime()) {
    _this->_impl_.a_fwdtime_.Set(from._internal_a_fwdtime(), 
      _this->GetArenaForAllocation());
  }
  _impl_.a_scenebuilttime_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_scenebuilttime_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_a_scenebuilttime()) {
    _this->_impl_.a_scenebuilttime_.Set(from._internal_a_scenebuilttime(), 
      _this->GetArenaForAllocation());
  }
  _impl_.a_url_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_url_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_a_url()) {
    _this->_impl_.a_url_.Set(from._internal_a_url(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.a_resourceuploadtime_, &from._impl_.a_resourceuploadtime_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.a_skippedcomposites_) -
    reinterpret_cast<char*>(&_impl_.a_resourceuploadtime_)) + sizeof(_impl_.a_skippedcomposites_));
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla.layers.FrameStats)
}

inline void FrameStats::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.a_id_){}
    , decltype(_impl_.a_compositestart_){}
    , decltype(_impl_.a_renderstart_){}
    , decltype(_impl_.a_compositeend_){}
    , decltype(_impl_.a_transactionstart_){}
    , decltype(_impl_.a_refreshstart_){}
    , decltype(_impl_.a_fwdtime_){}
    , decltype(_impl_.a_scenebuilttime_){}
    , decltype(_impl_.a_url_){}
    , decltype(_impl_.a_resourceuploadtime_){0}
    , decltype(_impl_.a_gpucacheuploadtime_){0}
    , decltype(_impl_.a_contentframetime_){0}
    , decltype(_impl_.a_skippedcomposites_){0u}
  };
  _impl_.a_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.a_compositestart_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_compositestart_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.a_renderstart_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_renderstart_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.a_compositeend_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_compositeend_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.a_transactionstart_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_transactionstart_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.a_refreshstart_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_refreshstart_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.a_fwdtime_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_fwdtime_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.a_scenebuilttime_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_scenebuilttime_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.a_url_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_url_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FrameStats::~FrameStats() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla.layers.FrameStats)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FrameStats::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.a_id_.Destroy();
  _impl_.a_compositestart_.Destroy();
  _impl_.a_renderstart_.Destroy();
  _impl_.a_compositeend_.Destroy();
  _impl_.a_transactionstart_.Destroy();
  _impl_.a_refreshstart_.Destroy();
  _impl_.a_fwdtime_.Destroy();
  _impl_.a_scenebuilttime_.Destroy();
  _impl_.a_url_.Destroy();
}

void FrameStats::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FrameStats::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla.layers.FrameStats)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.a_id_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.a_compositestart_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.a_renderstart_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.a_compositeend_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000010u) {
      _impl_.a_transactionstart_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000020u) {
      _impl_.a_refreshstart_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000040u) {
      _impl_.a_fwdtime_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000080u) {
      _impl_.a_scenebuilttime_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x00000100u) {
    _impl_.a_url_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x00001e00u) {
    ::memset(&_impl_.a_resourceuploadtime_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.a_skippedcomposites_) -
        reinterpret_cast<char*>(&_impl_.a_resourceuploadtime_)) + sizeof(_impl_.a_skippedcomposites_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* FrameStats::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required bytes a_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_a_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required bytes a_compositeStart = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_a_compositestart();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required bytes a_renderStart = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_a_renderstart();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required bytes a_compositeEnd = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_a_compositeend();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional sint32 a_contentFrameTime = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _Internal::set_has_a_contentframetime(&has_bits);
          _impl_.a_contentframetime_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional double a_resourceUploadTime = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _Internal::set_has_a_resourceuploadtime(&has_bits);
          _impl_.a_resourceuploadtime_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double a_gpuCacheUploadTime = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 57)) {
          _Internal::set_has_a_gpucacheuploadtime(&has_bits);
          _impl_.a_gpucacheuploadtime_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // required bytes a_transactionStart = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_a_transactionstart();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required bytes a_refreshStart = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          auto str = _internal_mutable_a_refreshstart();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required bytes a_fwdTime = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          auto str = _internal_mutable_a_fwdtime();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required bytes a_sceneBuiltTime = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          auto str = _internal_mutable_a_scenebuilttime();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 a_skippedComposites = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 96)) {
          _Internal::set_has_a_skippedcomposites(&has_bits);
          _impl_.a_skippedcomposites_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string a_url = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 106)) {
          auto str = _internal_mutable_a_url();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FrameStats::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla.layers.FrameStats)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required bytes a_id = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_a_id(), target);
  }

  // required bytes a_compositeStart = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_a_compositestart(), target);
  }

  // required bytes a_renderStart = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_a_renderstart(), target);
  }

  // required bytes a_compositeEnd = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_a_compositeend(), target);
  }

  // optional sint32 a_contentFrameTime = 5;
  if (cached_has_bits & 0x00000800u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(5, this->_internal_a_contentframetime(), target);
  }

  // optional double a_resourceUploadTime = 6;
  if (cached_has_bits & 0x00000200u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_a_resourceuploadtime(), target);
  }

  // optional double a_gpuCacheUploadTime = 7;
  if (cached_has_bits & 0x00000400u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(7, this->_internal_a_gpucacheuploadtime(), target);
  }

  // required bytes a_transactionStart = 8;
  if (cached_has_bits & 0x00000010u) {
    target = stream->WriteBytesMaybeAliased(
        8, this->_internal_a_transactionstart(), target);
  }

  // required bytes a_refreshStart = 9;
  if (cached_has_bits & 0x00000020u) {
    target = stream->WriteBytesMaybeAliased(
        9, this->_internal_a_refreshstart(), target);
  }

  // required bytes a_fwdTime = 10;
  if (cached_has_bits & 0x00000040u) {
    target = stream->WriteBytesMaybeAliased(
        10, this->_internal_a_fwdtime(), target);
  }

  // required bytes a_sceneBuiltTime = 11;
  if (cached_has_bits & 0x00000080u) {
    target = stream->WriteBytesMaybeAliased(
        11, this->_internal_a_scenebuilttime(), target);
  }

  // optional uint32 a_skippedComposites = 12;
  if (cached_has_bits & 0x00001000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(12, this->_internal_a_skippedcomposites(), target);
  }

  // optional string a_url = 13;
  if (cached_has_bits & 0x00000100u) {
    target = stream->WriteStringMaybeAliased(
        13, this->_internal_a_url(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla.layers.FrameStats)
  return target;
}

size_t FrameStats::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:protobuf.mozilla.layers.FrameStats)
  size_t total_size = 0;

  if (_internal_has_a_id()) {
    // required bytes a_id = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_id());
  }

  if (_internal_has_a_compositestart()) {
    // required bytes a_compositeStart = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_compositestart());
  }

  if (_internal_has_a_renderstart()) {
    // required bytes a_renderStart = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_renderstart());
  }

  if (_internal_has_a_compositeend()) {
    // required bytes a_compositeEnd = 4;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_compositeend());
  }

  if (_internal_has_a_transactionstart()) {
    // required bytes a_transactionStart = 8;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_transactionstart());
  }

  if (_internal_has_a_refreshstart()) {
    // required bytes a_refreshStart = 9;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_refreshstart());
  }

  if (_internal_has_a_fwdtime()) {
    // required bytes a_fwdTime = 10;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_fwdtime());
  }

  if (_internal_has_a_scenebuilttime()) {
    // required bytes a_sceneBuiltTime = 11;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_scenebuilttime());
  }

  return total_size;
}
size_t FrameStats::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla.layers.FrameStats)
  size_t total_size = 0;

  if (((_impl_._has_bits_[0] & 0x000000ff) ^ 0x000000ff) == 0) {  // All required fields are present.
    // required bytes a_id = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_id());

    // required bytes a_compositeStart = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_compositestart());

    // required bytes a_renderStart = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_renderstart());

    // required bytes a_compositeEnd = 4;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_compositeend());

    // required bytes a_transactionStart = 8;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_transactionstart());

    // required bytes a_refreshStart = 9;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_refreshstart());

    // required bytes a_fwdTime = 10;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_fwdtime());

    // required bytes a_sceneBuiltTime = 11;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_scenebuilttime());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00001f00u) {
    // optional string a_url = 13;
    if (cached_has_bits & 0x00000100u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_a_url());
    }

    // optional double a_resourceUploadTime = 6;
    if (cached_has_bits & 0x00000200u) {
      total_size += 1 + 8;
    }

    // optional double a_gpuCacheUploadTime = 7;
    if (cached_has_bits & 0x00000400u) {
      total_size += 1 + 8;
    }

    // optional sint32 a_contentFrameTime = 5;
    if (cached_has_bits & 0x00000800u) {
      total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_a_contentframetime());
    }

    // optional uint32 a_skippedComposites = 12;
    if (cached_has_bits & 0x00001000u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_a_skippedcomposites());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FrameStats::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const FrameStats*>(
      &from));
}

void FrameStats::MergeFrom(const FrameStats& from) {
  FrameStats* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla.layers.FrameStats)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_a_id(from._internal_a_id());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_a_compositestart(from._internal_a_compositestart());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_a_renderstart(from._internal_a_renderstart());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_set_a_compositeend(from._internal_a_compositeend());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_internal_set_a_transactionstart(from._internal_a_transactionstart());
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_internal_set_a_refreshstart(from._internal_a_refreshstart());
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_internal_set_a_fwdtime(from._internal_a_fwdtime());
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_internal_set_a_scenebuilttime(from._internal_a_scenebuilttime());
    }
  }
  if (cached_has_bits & 0x00001f00u) {
    if (cached_has_bits & 0x00000100u) {
      _this->_internal_set_a_url(from._internal_a_url());
    }
    if (cached_has_bits & 0x00000200u) {
      _this->_impl_.a_resourceuploadtime_ = from._impl_.a_resourceuploadtime_;
    }
    if (cached_has_bits & 0x00000400u) {
      _this->_impl_.a_gpucacheuploadtime_ = from._impl_.a_gpucacheuploadtime_;
    }
    if (cached_has_bits & 0x00000800u) {
      _this->_impl_.a_contentframetime_ = from._impl_.a_contentframetime_;
    }
    if (cached_has_bits & 0x00001000u) {
      _this->_impl_.a_skippedcomposites_ = from._impl_.a_skippedcomposites_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void FrameStats::CopyFrom(const FrameStats& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla.layers.FrameStats)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FrameStats::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void FrameStats::InternalSwap(FrameStats* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_id_, lhs_arena,
      &other->_impl_.a_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_compositestart_, lhs_arena,
      &other->_impl_.a_compositestart_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_renderstart_, lhs_arena,
      &other->_impl_.a_renderstart_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_compositeend_, lhs_arena,
      &other->_impl_.a_compositeend_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_transactionstart_, lhs_arena,
      &other->_impl_.a_transactionstart_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_refreshstart_, lhs_arena,
      &other->_impl_.a_refreshstart_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_fwdtime_, lhs_arena,
      &other->_impl_.a_fwdtime_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_scenebuilttime_, lhs_arena,
      &other->_impl_.a_scenebuilttime_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_url_, lhs_arena,
      &other->_impl_.a_url_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FrameStats, _impl_.a_skippedcomposites_)
      + sizeof(FrameStats::_impl_.a_skippedcomposites_)
      - PROTOBUF_FIELD_OFFSET(FrameStats, _impl_.a_resourceuploadtime_)>(
          reinterpret_cast<char*>(&_impl_.a_resourceuploadtime_),
          reinterpret_cast<char*>(&other->_impl_.a_resourceuploadtime_));
}

std::string FrameStats::GetTypeName() const {
  return "protobuf.mozilla.layers.FrameStats";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace layers
}  // namespace mozilla
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::layers::FrameStats*
Arena::CreateMaybeMessage< ::protobuf::mozilla::layers::FrameStats >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::layers::FrameStats >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
