// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PContent_protobuf.h.proto

#include "PContent_protobuf.h.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace protobuf {
PROTOBUF_CONSTEXPR ChromeRegistryItem::ChromeRegistryItem(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.content_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct ChromeRegistryItemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChromeRegistryItemDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChromeRegistryItemDefaultTypeInternal() {}
  union {
    ChromeRegistryItem _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChromeRegistryItemDefaultTypeInternal _ChromeRegistryItem_default_instance_;
}  // namespace protobuf
namespace protobuf {

// ===================================================================

class ChromeRegistryItem::_Internal {
 public:
};

ChromeRegistryItem::ChromeRegistryItem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.ChromeRegistryItem)
}
ChromeRegistryItem::ChromeRegistryItem(const ChromeRegistryItem& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  ChromeRegistryItem* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.content_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  clear_has_content();
  switch (from.content_case()) {
    case kAMVChromePackage: {
      _this->_internal_set_a_mvchromepackage(from._internal_a_mvchromepackage());
      break;
    }
    case kAMVOverrideMapping: {
      _this->_internal_set_a_mvoverridemapping(from._internal_a_mvoverridemapping());
      break;
    }
    case kAMVSubstitutionMapping: {
      _this->_internal_set_a_mvsubstitutionmapping(from._internal_a_mvsubstitutionmapping());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:protobuf.ChromeRegistryItem)
}

inline void ChromeRegistryItem::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.content_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_content();
}

ChromeRegistryItem::~ChromeRegistryItem() {
  // @@protoc_insertion_point(destructor:protobuf.ChromeRegistryItem)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ChromeRegistryItem::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_content()) {
    clear_content();
  }
}

void ChromeRegistryItem::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ChromeRegistryItem::clear_content() {
// @@protoc_insertion_point(one_of_clear_start:protobuf.ChromeRegistryItem)
  switch (content_case()) {
    case kAMVChromePackage: {
      _impl_.content_.a_mvchromepackage_.Destroy();
      break;
    }
    case kAMVOverrideMapping: {
      _impl_.content_.a_mvoverridemapping_.Destroy();
      break;
    }
    case kAMVSubstitutionMapping: {
      _impl_.content_.a_mvsubstitutionmapping_.Destroy();
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = CONTENT_NOT_SET;
}


void ChromeRegistryItem::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.ChromeRegistryItem)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_content();
  _internal_metadata_.Clear<std::string>();
}

const char* ChromeRegistryItem::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes a_mVChromePackage = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_a_mvchromepackage();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes a_mVOverrideMapping = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_a_mvoverridemapping();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes a_mVSubstitutionMapping = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_a_mvsubstitutionmapping();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ChromeRegistryItem::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.ChromeRegistryItem)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (content_case()) {
    case kAMVChromePackage: {
      target = stream->WriteBytesMaybeAliased(
          1, this->_internal_a_mvchromepackage(), target);
      break;
    }
    case kAMVOverrideMapping: {
      target = stream->WriteBytesMaybeAliased(
          2, this->_internal_a_mvoverridemapping(), target);
      break;
    }
    case kAMVSubstitutionMapping: {
      target = stream->WriteBytesMaybeAliased(
          3, this->_internal_a_mvsubstitutionmapping(), target);
      break;
    }
    default: ;
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.ChromeRegistryItem)
  return target;
}

size_t ChromeRegistryItem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.ChromeRegistryItem)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (content_case()) {
    // bytes a_mVChromePackage = 1;
    case kAMVChromePackage: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_a_mvchromepackage());
      break;
    }
    // bytes a_mVOverrideMapping = 2;
    case kAMVOverrideMapping: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_a_mvoverridemapping());
      break;
    }
    // bytes a_mVSubstitutionMapping = 3;
    case kAMVSubstitutionMapping: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_a_mvsubstitutionmapping());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ChromeRegistryItem::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const ChromeRegistryItem*>(
      &from));
}

void ChromeRegistryItem::MergeFrom(const ChromeRegistryItem& from) {
  ChromeRegistryItem* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.ChromeRegistryItem)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.content_case()) {
    case kAMVChromePackage: {
      _this->_internal_set_a_mvchromepackage(from._internal_a_mvchromepackage());
      break;
    }
    case kAMVOverrideMapping: {
      _this->_internal_set_a_mvoverridemapping(from._internal_a_mvoverridemapping());
      break;
    }
    case kAMVSubstitutionMapping: {
      _this->_internal_set_a_mvsubstitutionmapping(from._internal_a_mvsubstitutionmapping());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void ChromeRegistryItem::CopyFrom(const ChromeRegistryItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.ChromeRegistryItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChromeRegistryItem::IsInitialized() const {
  return true;
}

void ChromeRegistryItem::InternalSwap(ChromeRegistryItem* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.content_, other->_impl_.content_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

std::string ChromeRegistryItem::GetTypeName() const {
  return "protobuf.ChromeRegistryItem";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::ChromeRegistryItem*
Arena::CreateMaybeMessage< ::protobuf::ChromeRegistryItem >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::ChromeRegistryItem >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
