// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PFileSystemParams_protobuf.mozilla.dom.h.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_PFileSystemParams_5fprotobuf_2emozilla_2edom_2eh_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_PFileSystemParams_5fprotobuf_2emozilla_2edom_2eh_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_PFileSystemParams_5fprotobuf_2emozilla_2edom_2eh_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_PFileSystemParams_5fprotobuf_2emozilla_2edom_2eh_2eproto {
  static const uint32_t offsets[];
};
namespace protobuf {
namespace mozilla {
namespace dom {
class FileSystemGetDirectoryListingParams;
struct FileSystemGetDirectoryListingParamsDefaultTypeInternal;
extern FileSystemGetDirectoryListingParamsDefaultTypeInternal _FileSystemGetDirectoryListingParams_default_instance_;
class FileSystemGetFileOrDirectoryParams;
struct FileSystemGetFileOrDirectoryParamsDefaultTypeInternal;
extern FileSystemGetFileOrDirectoryParamsDefaultTypeInternal _FileSystemGetFileOrDirectoryParams_default_instance_;
class FileSystemGetFilesParams;
struct FileSystemGetFilesParamsDefaultTypeInternal;
extern FileSystemGetFilesParamsDefaultTypeInternal _FileSystemGetFilesParams_default_instance_;
class FileSystemParams;
struct FileSystemParamsDefaultTypeInternal;
extern FileSystemParamsDefaultTypeInternal _FileSystemParams_default_instance_;
}  // namespace dom
}  // namespace mozilla
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams* Arena::CreateMaybeMessage<::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams>(Arena*);
template<> ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams* Arena::CreateMaybeMessage<::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams>(Arena*);
template<> ::protobuf::mozilla::dom::FileSystemGetFilesParams* Arena::CreateMaybeMessage<::protobuf::mozilla::dom::FileSystemGetFilesParams>(Arena*);
template<> ::protobuf::mozilla::dom::FileSystemParams* Arena::CreateMaybeMessage<::protobuf::mozilla::dom::FileSystemParams>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace protobuf {
namespace mozilla {
namespace dom {

// ===================================================================

class FileSystemGetDirectoryListingParams final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams) */ {
 public:
  inline FileSystemGetDirectoryListingParams() : FileSystemGetDirectoryListingParams(nullptr) {}
  ~FileSystemGetDirectoryListingParams() override;
  explicit PROTOBUF_CONSTEXPR FileSystemGetDirectoryListingParams(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileSystemGetDirectoryListingParams(const FileSystemGetDirectoryListingParams& from);
  FileSystemGetDirectoryListingParams(FileSystemGetDirectoryListingParams&& from) noexcept
    : FileSystemGetDirectoryListingParams() {
    *this = ::std::move(from);
  }

  inline FileSystemGetDirectoryListingParams& operator=(const FileSystemGetDirectoryListingParams& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileSystemGetDirectoryListingParams& operator=(FileSystemGetDirectoryListingParams&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const FileSystemGetDirectoryListingParams& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileSystemGetDirectoryListingParams* internal_default_instance() {
    return reinterpret_cast<const FileSystemGetDirectoryListingParams*>(
               &_FileSystemGetDirectoryListingParams_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FileSystemGetDirectoryListingParams& a, FileSystemGetDirectoryListingParams& b) {
    a.Swap(&b);
  }
  inline void Swap(FileSystemGetDirectoryListingParams* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileSystemGetDirectoryListingParams* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileSystemGetDirectoryListingParams* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileSystemGetDirectoryListingParams>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const FileSystemGetDirectoryListingParams& from);
  void MergeFrom(const FileSystemGetDirectoryListingParams& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FileSystemGetDirectoryListingParams* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf.mozilla.dom.FileSystemGetDirectoryListingParams";
  }
  protected:
  explicit FileSystemGetDirectoryListingParams(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFilesystemFieldNumber = 1,
    kRealPathFieldNumber = 2,
    kDomPathFieldNumber = 3,
    kFiltersFieldNumber = 4,
  };
  // required string filesystem = 1;
  bool has_filesystem() const;
  private:
  bool _internal_has_filesystem() const;
  public:
  void clear_filesystem();
  const std::string& filesystem() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_filesystem(ArgT0&& arg0, ArgT... args);
  std::string* mutable_filesystem();
  PROTOBUF_NODISCARD std::string* release_filesystem();
  void set_allocated_filesystem(std::string* filesystem);
  private:
  const std::string& _internal_filesystem() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filesystem(const std::string& value);
  std::string* _internal_mutable_filesystem();
  public:

  // required string realPath = 2;
  bool has_realpath() const;
  private:
  bool _internal_has_realpath() const;
  public:
  void clear_realpath();
  const std::string& realpath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_realpath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_realpath();
  PROTOBUF_NODISCARD std::string* release_realpath();
  void set_allocated_realpath(std::string* realpath);
  private:
  const std::string& _internal_realpath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_realpath(const std::string& value);
  std::string* _internal_mutable_realpath();
  public:

  // required string domPath = 3;
  bool has_dompath() const;
  private:
  bool _internal_has_dompath() const;
  public:
  void clear_dompath();
  const std::string& dompath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_dompath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_dompath();
  PROTOBUF_NODISCARD std::string* release_dompath();
  void set_allocated_dompath(std::string* dompath);
  private:
  const std::string& _internal_dompath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_dompath(const std::string& value);
  std::string* _internal_mutable_dompath();
  public:

  // required string filters = 4;
  bool has_filters() const;
  private:
  bool _internal_has_filters() const;
  public:
  void clear_filters();
  const std::string& filters() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_filters(ArgT0&& arg0, ArgT... args);
  std::string* mutable_filters();
  PROTOBUF_NODISCARD std::string* release_filters();
  void set_allocated_filters(std::string* filters);
  private:
  const std::string& _internal_filters() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filters(const std::string& value);
  std::string* _internal_mutable_filters();
  public:

  // @@protoc_insertion_point(class_scope:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filesystem_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr realpath_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr dompath_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filters_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PFileSystemParams_5fprotobuf_2emozilla_2edom_2eh_2eproto;
};
// -------------------------------------------------------------------

class FileSystemGetFilesParams final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:protobuf.mozilla.dom.FileSystemGetFilesParams) */ {
 public:
  inline FileSystemGetFilesParams() : FileSystemGetFilesParams(nullptr) {}
  ~FileSystemGetFilesParams() override;
  explicit PROTOBUF_CONSTEXPR FileSystemGetFilesParams(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileSystemGetFilesParams(const FileSystemGetFilesParams& from);
  FileSystemGetFilesParams(FileSystemGetFilesParams&& from) noexcept
    : FileSystemGetFilesParams() {
    *this = ::std::move(from);
  }

  inline FileSystemGetFilesParams& operator=(const FileSystemGetFilesParams& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileSystemGetFilesParams& operator=(FileSystemGetFilesParams&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const FileSystemGetFilesParams& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileSystemGetFilesParams* internal_default_instance() {
    return reinterpret_cast<const FileSystemGetFilesParams*>(
               &_FileSystemGetFilesParams_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(FileSystemGetFilesParams& a, FileSystemGetFilesParams& b) {
    a.Swap(&b);
  }
  inline void Swap(FileSystemGetFilesParams* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileSystemGetFilesParams* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileSystemGetFilesParams* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileSystemGetFilesParams>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const FileSystemGetFilesParams& from);
  void MergeFrom(const FileSystemGetFilesParams& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FileSystemGetFilesParams* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf.mozilla.dom.FileSystemGetFilesParams";
  }
  protected:
  explicit FileSystemGetFilesParams(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFilesystemFieldNumber = 1,
    kRealPathFieldNumber = 2,
    kDomPathFieldNumber = 3,
    kRecursiveFlagFieldNumber = 4,
  };
  // required string filesystem = 1;
  bool has_filesystem() const;
  private:
  bool _internal_has_filesystem() const;
  public:
  void clear_filesystem();
  const std::string& filesystem() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_filesystem(ArgT0&& arg0, ArgT... args);
  std::string* mutable_filesystem();
  PROTOBUF_NODISCARD std::string* release_filesystem();
  void set_allocated_filesystem(std::string* filesystem);
  private:
  const std::string& _internal_filesystem() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filesystem(const std::string& value);
  std::string* _internal_mutable_filesystem();
  public:

  // required string realPath = 2;
  bool has_realpath() const;
  private:
  bool _internal_has_realpath() const;
  public:
  void clear_realpath();
  const std::string& realpath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_realpath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_realpath();
  PROTOBUF_NODISCARD std::string* release_realpath();
  void set_allocated_realpath(std::string* realpath);
  private:
  const std::string& _internal_realpath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_realpath(const std::string& value);
  std::string* _internal_mutable_realpath();
  public:

  // required string domPath = 3;
  bool has_dompath() const;
  private:
  bool _internal_has_dompath() const;
  public:
  void clear_dompath();
  const std::string& dompath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_dompath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_dompath();
  PROTOBUF_NODISCARD std::string* release_dompath();
  void set_allocated_dompath(std::string* dompath);
  private:
  const std::string& _internal_dompath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_dompath(const std::string& value);
  std::string* _internal_mutable_dompath();
  public:

  // required bool recursiveFlag = 4;
  bool has_recursiveflag() const;
  private:
  bool _internal_has_recursiveflag() const;
  public:
  void clear_recursiveflag();
  bool recursiveflag() const;
  void set_recursiveflag(bool value);
  private:
  bool _internal_recursiveflag() const;
  void _internal_set_recursiveflag(bool value);
  public:

  // @@protoc_insertion_point(class_scope:protobuf.mozilla.dom.FileSystemGetFilesParams)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filesystem_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr realpath_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr dompath_;
    bool recursiveflag_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PFileSystemParams_5fprotobuf_2emozilla_2edom_2eh_2eproto;
};
// -------------------------------------------------------------------

class FileSystemGetFileOrDirectoryParams final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:protobuf.mozilla.dom.FileSystemGetFileOrDirectoryParams) */ {
 public:
  inline FileSystemGetFileOrDirectoryParams() : FileSystemGetFileOrDirectoryParams(nullptr) {}
  ~FileSystemGetFileOrDirectoryParams() override;
  explicit PROTOBUF_CONSTEXPR FileSystemGetFileOrDirectoryParams(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileSystemGetFileOrDirectoryParams(const FileSystemGetFileOrDirectoryParams& from);
  FileSystemGetFileOrDirectoryParams(FileSystemGetFileOrDirectoryParams&& from) noexcept
    : FileSystemGetFileOrDirectoryParams() {
    *this = ::std::move(from);
  }

  inline FileSystemGetFileOrDirectoryParams& operator=(const FileSystemGetFileOrDirectoryParams& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileSystemGetFileOrDirectoryParams& operator=(FileSystemGetFileOrDirectoryParams&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const FileSystemGetFileOrDirectoryParams& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileSystemGetFileOrDirectoryParams* internal_default_instance() {
    return reinterpret_cast<const FileSystemGetFileOrDirectoryParams*>(
               &_FileSystemGetFileOrDirectoryParams_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(FileSystemGetFileOrDirectoryParams& a, FileSystemGetFileOrDirectoryParams& b) {
    a.Swap(&b);
  }
  inline void Swap(FileSystemGetFileOrDirectoryParams* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileSystemGetFileOrDirectoryParams* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileSystemGetFileOrDirectoryParams* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileSystemGetFileOrDirectoryParams>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const FileSystemGetFileOrDirectoryParams& from);
  void MergeFrom(const FileSystemGetFileOrDirectoryParams& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FileSystemGetFileOrDirectoryParams* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf.mozilla.dom.FileSystemGetFileOrDirectoryParams";
  }
  protected:
  explicit FileSystemGetFileOrDirectoryParams(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFilesystemFieldNumber = 1,
    kRealPathFieldNumber = 2,
  };
  // required string filesystem = 1;
  bool has_filesystem() const;
  private:
  bool _internal_has_filesystem() const;
  public:
  void clear_filesystem();
  const std::string& filesystem() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_filesystem(ArgT0&& arg0, ArgT... args);
  std::string* mutable_filesystem();
  PROTOBUF_NODISCARD std::string* release_filesystem();
  void set_allocated_filesystem(std::string* filesystem);
  private:
  const std::string& _internal_filesystem() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filesystem(const std::string& value);
  std::string* _internal_mutable_filesystem();
  public:

  // required string realPath = 2;
  bool has_realpath() const;
  private:
  bool _internal_has_realpath() const;
  public:
  void clear_realpath();
  const std::string& realpath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_realpath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_realpath();
  PROTOBUF_NODISCARD std::string* release_realpath();
  void set_allocated_realpath(std::string* realpath);
  private:
  const std::string& _internal_realpath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_realpath(const std::string& value);
  std::string* _internal_mutable_realpath();
  public:

  // @@protoc_insertion_point(class_scope:protobuf.mozilla.dom.FileSystemGetFileOrDirectoryParams)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filesystem_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr realpath_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PFileSystemParams_5fprotobuf_2emozilla_2edom_2eh_2eproto;
};
// -------------------------------------------------------------------

class FileSystemParams final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:protobuf.mozilla.dom.FileSystemParams) */ {
 public:
  inline FileSystemParams() : FileSystemParams(nullptr) {}
  ~FileSystemParams() override;
  explicit PROTOBUF_CONSTEXPR FileSystemParams(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileSystemParams(const FileSystemParams& from);
  FileSystemParams(FileSystemParams&& from) noexcept
    : FileSystemParams() {
    *this = ::std::move(from);
  }

  inline FileSystemParams& operator=(const FileSystemParams& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileSystemParams& operator=(FileSystemParams&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const FileSystemParams& default_instance() {
    return *internal_default_instance();
  }
  enum ContentCase {
    kMVFileSystemGetDirectoryListingParams = 1,
    kMVFileSystemGetFilesParams = 2,
    kMVFileSystemGetFileOrDirectoryParams = 3,
    CONTENT_NOT_SET = 0,
  };

  static inline const FileSystemParams* internal_default_instance() {
    return reinterpret_cast<const FileSystemParams*>(
               &_FileSystemParams_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(FileSystemParams& a, FileSystemParams& b) {
    a.Swap(&b);
  }
  inline void Swap(FileSystemParams* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileSystemParams* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileSystemParams* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileSystemParams>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const FileSystemParams& from);
  void MergeFrom(const FileSystemParams& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FileSystemParams* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protobuf.mozilla.dom.FileSystemParams";
  }
  protected:
  explicit FileSystemParams(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMVFileSystemGetDirectoryListingParamsFieldNumber = 1,
    kMVFileSystemGetFilesParamsFieldNumber = 2,
    kMVFileSystemGetFileOrDirectoryParamsFieldNumber = 3,
  };
  // .protobuf.mozilla.dom.FileSystemGetDirectoryListingParams mVFileSystemGetDirectoryListingParams = 1;
  bool has_mvfilesystemgetdirectorylistingparams() const;
  private:
  bool _internal_has_mvfilesystemgetdirectorylistingparams() const;
  public:
  void clear_mvfilesystemgetdirectorylistingparams();
  const ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams& mvfilesystemgetdirectorylistingparams() const;
  PROTOBUF_NODISCARD ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams* release_mvfilesystemgetdirectorylistingparams();
  ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams* mutable_mvfilesystemgetdirectorylistingparams();
  void set_allocated_mvfilesystemgetdirectorylistingparams(::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams* mvfilesystemgetdirectorylistingparams);
  private:
  const ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams& _internal_mvfilesystemgetdirectorylistingparams() const;
  ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams* _internal_mutable_mvfilesystemgetdirectorylistingparams();
  public:
  void unsafe_arena_set_allocated_mvfilesystemgetdirectorylistingparams(
      ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams* mvfilesystemgetdirectorylistingparams);
  ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams* unsafe_arena_release_mvfilesystemgetdirectorylistingparams();

  // .protobuf.mozilla.dom.FileSystemGetFilesParams mVFileSystemGetFilesParams = 2;
  bool has_mvfilesystemgetfilesparams() const;
  private:
  bool _internal_has_mvfilesystemgetfilesparams() const;
  public:
  void clear_mvfilesystemgetfilesparams();
  const ::protobuf::mozilla::dom::FileSystemGetFilesParams& mvfilesystemgetfilesparams() const;
  PROTOBUF_NODISCARD ::protobuf::mozilla::dom::FileSystemGetFilesParams* release_mvfilesystemgetfilesparams();
  ::protobuf::mozilla::dom::FileSystemGetFilesParams* mutable_mvfilesystemgetfilesparams();
  void set_allocated_mvfilesystemgetfilesparams(::protobuf::mozilla::dom::FileSystemGetFilesParams* mvfilesystemgetfilesparams);
  private:
  const ::protobuf::mozilla::dom::FileSystemGetFilesParams& _internal_mvfilesystemgetfilesparams() const;
  ::protobuf::mozilla::dom::FileSystemGetFilesParams* _internal_mutable_mvfilesystemgetfilesparams();
  public:
  void unsafe_arena_set_allocated_mvfilesystemgetfilesparams(
      ::protobuf::mozilla::dom::FileSystemGetFilesParams* mvfilesystemgetfilesparams);
  ::protobuf::mozilla::dom::FileSystemGetFilesParams* unsafe_arena_release_mvfilesystemgetfilesparams();

  // .protobuf.mozilla.dom.FileSystemGetFileOrDirectoryParams mVFileSystemGetFileOrDirectoryParams = 3;
  bool has_mvfilesystemgetfileordirectoryparams() const;
  private:
  bool _internal_has_mvfilesystemgetfileordirectoryparams() const;
  public:
  void clear_mvfilesystemgetfileordirectoryparams();
  const ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams& mvfilesystemgetfileordirectoryparams() const;
  PROTOBUF_NODISCARD ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams* release_mvfilesystemgetfileordirectoryparams();
  ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams* mutable_mvfilesystemgetfileordirectoryparams();
  void set_allocated_mvfilesystemgetfileordirectoryparams(::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams* mvfilesystemgetfileordirectoryparams);
  private:
  const ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams& _internal_mvfilesystemgetfileordirectoryparams() const;
  ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams* _internal_mutable_mvfilesystemgetfileordirectoryparams();
  public:
  void unsafe_arena_set_allocated_mvfilesystemgetfileordirectoryparams(
      ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams* mvfilesystemgetfileordirectoryparams);
  ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams* unsafe_arena_release_mvfilesystemgetfileordirectoryparams();

  void clear_content();
  ContentCase content_case() const;
  // @@protoc_insertion_point(class_scope:protobuf.mozilla.dom.FileSystemParams)
 private:
  class _Internal;
  void set_has_mvfilesystemgetdirectorylistingparams();
  void set_has_mvfilesystemgetfilesparams();
  void set_has_mvfilesystemgetfileordirectoryparams();

  inline bool has_content() const;
  inline void clear_has_content();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ContentUnion {
      constexpr ContentUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams* mvfilesystemgetdirectorylistingparams_;
      ::protobuf::mozilla::dom::FileSystemGetFilesParams* mvfilesystemgetfilesparams_;
      ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams* mvfilesystemgetfileordirectoryparams_;
    } content_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PFileSystemParams_5fprotobuf_2emozilla_2edom_2eh_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FileSystemGetDirectoryListingParams

// required string filesystem = 1;
inline bool FileSystemGetDirectoryListingParams::_internal_has_filesystem() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool FileSystemGetDirectoryListingParams::has_filesystem() const {
  return _internal_has_filesystem();
}
inline void FileSystemGetDirectoryListingParams::clear_filesystem() {
  _impl_.filesystem_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& FileSystemGetDirectoryListingParams::filesystem() const {
  // @@protoc_insertion_point(field_get:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.filesystem)
  return _internal_filesystem();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileSystemGetDirectoryListingParams::set_filesystem(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.filesystem_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.filesystem)
}
inline std::string* FileSystemGetDirectoryListingParams::mutable_filesystem() {
  std::string* _s = _internal_mutable_filesystem();
  // @@protoc_insertion_point(field_mutable:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.filesystem)
  return _s;
}
inline const std::string& FileSystemGetDirectoryListingParams::_internal_filesystem() const {
  return _impl_.filesystem_.Get();
}
inline void FileSystemGetDirectoryListingParams::_internal_set_filesystem(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.filesystem_.Set(value, GetArenaForAllocation());
}
inline std::string* FileSystemGetDirectoryListingParams::_internal_mutable_filesystem() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.filesystem_.Mutable(GetArenaForAllocation());
}
inline std::string* FileSystemGetDirectoryListingParams::release_filesystem() {
  // @@protoc_insertion_point(field_release:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.filesystem)
  if (!_internal_has_filesystem()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.filesystem_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filesystem_.IsDefault()) {
    _impl_.filesystem_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void FileSystemGetDirectoryListingParams::set_allocated_filesystem(std::string* filesystem) {
  if (filesystem != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.filesystem_.SetAllocated(filesystem, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filesystem_.IsDefault()) {
    _impl_.filesystem_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.filesystem)
}

// required string realPath = 2;
inline bool FileSystemGetDirectoryListingParams::_internal_has_realpath() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool FileSystemGetDirectoryListingParams::has_realpath() const {
  return _internal_has_realpath();
}
inline void FileSystemGetDirectoryListingParams::clear_realpath() {
  _impl_.realpath_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& FileSystemGetDirectoryListingParams::realpath() const {
  // @@protoc_insertion_point(field_get:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.realPath)
  return _internal_realpath();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileSystemGetDirectoryListingParams::set_realpath(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.realpath_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.realPath)
}
inline std::string* FileSystemGetDirectoryListingParams::mutable_realpath() {
  std::string* _s = _internal_mutable_realpath();
  // @@protoc_insertion_point(field_mutable:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.realPath)
  return _s;
}
inline const std::string& FileSystemGetDirectoryListingParams::_internal_realpath() const {
  return _impl_.realpath_.Get();
}
inline void FileSystemGetDirectoryListingParams::_internal_set_realpath(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.realpath_.Set(value, GetArenaForAllocation());
}
inline std::string* FileSystemGetDirectoryListingParams::_internal_mutable_realpath() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.realpath_.Mutable(GetArenaForAllocation());
}
inline std::string* FileSystemGetDirectoryListingParams::release_realpath() {
  // @@protoc_insertion_point(field_release:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.realPath)
  if (!_internal_has_realpath()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.realpath_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.realpath_.IsDefault()) {
    _impl_.realpath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void FileSystemGetDirectoryListingParams::set_allocated_realpath(std::string* realpath) {
  if (realpath != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.realpath_.SetAllocated(realpath, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.realpath_.IsDefault()) {
    _impl_.realpath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.realPath)
}

// required string domPath = 3;
inline bool FileSystemGetDirectoryListingParams::_internal_has_dompath() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool FileSystemGetDirectoryListingParams::has_dompath() const {
  return _internal_has_dompath();
}
inline void FileSystemGetDirectoryListingParams::clear_dompath() {
  _impl_.dompath_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& FileSystemGetDirectoryListingParams::dompath() const {
  // @@protoc_insertion_point(field_get:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.domPath)
  return _internal_dompath();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileSystemGetDirectoryListingParams::set_dompath(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000004u;
 _impl_.dompath_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.domPath)
}
inline std::string* FileSystemGetDirectoryListingParams::mutable_dompath() {
  std::string* _s = _internal_mutable_dompath();
  // @@protoc_insertion_point(field_mutable:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.domPath)
  return _s;
}
inline const std::string& FileSystemGetDirectoryListingParams::_internal_dompath() const {
  return _impl_.dompath_.Get();
}
inline void FileSystemGetDirectoryListingParams::_internal_set_dompath(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.dompath_.Set(value, GetArenaForAllocation());
}
inline std::string* FileSystemGetDirectoryListingParams::_internal_mutable_dompath() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.dompath_.Mutable(GetArenaForAllocation());
}
inline std::string* FileSystemGetDirectoryListingParams::release_dompath() {
  // @@protoc_insertion_point(field_release:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.domPath)
  if (!_internal_has_dompath()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* p = _impl_.dompath_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.dompath_.IsDefault()) {
    _impl_.dompath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void FileSystemGetDirectoryListingParams::set_allocated_dompath(std::string* dompath) {
  if (dompath != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.dompath_.SetAllocated(dompath, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.dompath_.IsDefault()) {
    _impl_.dompath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.domPath)
}

// required string filters = 4;
inline bool FileSystemGetDirectoryListingParams::_internal_has_filters() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool FileSystemGetDirectoryListingParams::has_filters() const {
  return _internal_has_filters();
}
inline void FileSystemGetDirectoryListingParams::clear_filters() {
  _impl_.filters_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& FileSystemGetDirectoryListingParams::filters() const {
  // @@protoc_insertion_point(field_get:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.filters)
  return _internal_filters();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileSystemGetDirectoryListingParams::set_filters(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000008u;
 _impl_.filters_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.filters)
}
inline std::string* FileSystemGetDirectoryListingParams::mutable_filters() {
  std::string* _s = _internal_mutable_filters();
  // @@protoc_insertion_point(field_mutable:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.filters)
  return _s;
}
inline const std::string& FileSystemGetDirectoryListingParams::_internal_filters() const {
  return _impl_.filters_.Get();
}
inline void FileSystemGetDirectoryListingParams::_internal_set_filters(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.filters_.Set(value, GetArenaForAllocation());
}
inline std::string* FileSystemGetDirectoryListingParams::_internal_mutable_filters() {
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.filters_.Mutable(GetArenaForAllocation());
}
inline std::string* FileSystemGetDirectoryListingParams::release_filters() {
  // @@protoc_insertion_point(field_release:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.filters)
  if (!_internal_has_filters()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* p = _impl_.filters_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filters_.IsDefault()) {
    _impl_.filters_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void FileSystemGetDirectoryListingParams::set_allocated_filters(std::string* filters) {
  if (filters != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.filters_.SetAllocated(filters, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filters_.IsDefault()) {
    _impl_.filters_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.mozilla.dom.FileSystemGetDirectoryListingParams.filters)
}

// -------------------------------------------------------------------

// FileSystemGetFilesParams

// required string filesystem = 1;
inline bool FileSystemGetFilesParams::_internal_has_filesystem() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool FileSystemGetFilesParams::has_filesystem() const {
  return _internal_has_filesystem();
}
inline void FileSystemGetFilesParams::clear_filesystem() {
  _impl_.filesystem_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& FileSystemGetFilesParams::filesystem() const {
  // @@protoc_insertion_point(field_get:protobuf.mozilla.dom.FileSystemGetFilesParams.filesystem)
  return _internal_filesystem();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileSystemGetFilesParams::set_filesystem(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.filesystem_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.mozilla.dom.FileSystemGetFilesParams.filesystem)
}
inline std::string* FileSystemGetFilesParams::mutable_filesystem() {
  std::string* _s = _internal_mutable_filesystem();
  // @@protoc_insertion_point(field_mutable:protobuf.mozilla.dom.FileSystemGetFilesParams.filesystem)
  return _s;
}
inline const std::string& FileSystemGetFilesParams::_internal_filesystem() const {
  return _impl_.filesystem_.Get();
}
inline void FileSystemGetFilesParams::_internal_set_filesystem(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.filesystem_.Set(value, GetArenaForAllocation());
}
inline std::string* FileSystemGetFilesParams::_internal_mutable_filesystem() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.filesystem_.Mutable(GetArenaForAllocation());
}
inline std::string* FileSystemGetFilesParams::release_filesystem() {
  // @@protoc_insertion_point(field_release:protobuf.mozilla.dom.FileSystemGetFilesParams.filesystem)
  if (!_internal_has_filesystem()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.filesystem_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filesystem_.IsDefault()) {
    _impl_.filesystem_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void FileSystemGetFilesParams::set_allocated_filesystem(std::string* filesystem) {
  if (filesystem != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.filesystem_.SetAllocated(filesystem, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filesystem_.IsDefault()) {
    _impl_.filesystem_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.mozilla.dom.FileSystemGetFilesParams.filesystem)
}

// required string realPath = 2;
inline bool FileSystemGetFilesParams::_internal_has_realpath() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool FileSystemGetFilesParams::has_realpath() const {
  return _internal_has_realpath();
}
inline void FileSystemGetFilesParams::clear_realpath() {
  _impl_.realpath_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& FileSystemGetFilesParams::realpath() const {
  // @@protoc_insertion_point(field_get:protobuf.mozilla.dom.FileSystemGetFilesParams.realPath)
  return _internal_realpath();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileSystemGetFilesParams::set_realpath(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.realpath_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.mozilla.dom.FileSystemGetFilesParams.realPath)
}
inline std::string* FileSystemGetFilesParams::mutable_realpath() {
  std::string* _s = _internal_mutable_realpath();
  // @@protoc_insertion_point(field_mutable:protobuf.mozilla.dom.FileSystemGetFilesParams.realPath)
  return _s;
}
inline const std::string& FileSystemGetFilesParams::_internal_realpath() const {
  return _impl_.realpath_.Get();
}
inline void FileSystemGetFilesParams::_internal_set_realpath(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.realpath_.Set(value, GetArenaForAllocation());
}
inline std::string* FileSystemGetFilesParams::_internal_mutable_realpath() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.realpath_.Mutable(GetArenaForAllocation());
}
inline std::string* FileSystemGetFilesParams::release_realpath() {
  // @@protoc_insertion_point(field_release:protobuf.mozilla.dom.FileSystemGetFilesParams.realPath)
  if (!_internal_has_realpath()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.realpath_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.realpath_.IsDefault()) {
    _impl_.realpath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void FileSystemGetFilesParams::set_allocated_realpath(std::string* realpath) {
  if (realpath != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.realpath_.SetAllocated(realpath, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.realpath_.IsDefault()) {
    _impl_.realpath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.mozilla.dom.FileSystemGetFilesParams.realPath)
}

// required string domPath = 3;
inline bool FileSystemGetFilesParams::_internal_has_dompath() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool FileSystemGetFilesParams::has_dompath() const {
  return _internal_has_dompath();
}
inline void FileSystemGetFilesParams::clear_dompath() {
  _impl_.dompath_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& FileSystemGetFilesParams::dompath() const {
  // @@protoc_insertion_point(field_get:protobuf.mozilla.dom.FileSystemGetFilesParams.domPath)
  return _internal_dompath();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileSystemGetFilesParams::set_dompath(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000004u;
 _impl_.dompath_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.mozilla.dom.FileSystemGetFilesParams.domPath)
}
inline std::string* FileSystemGetFilesParams::mutable_dompath() {
  std::string* _s = _internal_mutable_dompath();
  // @@protoc_insertion_point(field_mutable:protobuf.mozilla.dom.FileSystemGetFilesParams.domPath)
  return _s;
}
inline const std::string& FileSystemGetFilesParams::_internal_dompath() const {
  return _impl_.dompath_.Get();
}
inline void FileSystemGetFilesParams::_internal_set_dompath(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.dompath_.Set(value, GetArenaForAllocation());
}
inline std::string* FileSystemGetFilesParams::_internal_mutable_dompath() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.dompath_.Mutable(GetArenaForAllocation());
}
inline std::string* FileSystemGetFilesParams::release_dompath() {
  // @@protoc_insertion_point(field_release:protobuf.mozilla.dom.FileSystemGetFilesParams.domPath)
  if (!_internal_has_dompath()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* p = _impl_.dompath_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.dompath_.IsDefault()) {
    _impl_.dompath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void FileSystemGetFilesParams::set_allocated_dompath(std::string* dompath) {
  if (dompath != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.dompath_.SetAllocated(dompath, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.dompath_.IsDefault()) {
    _impl_.dompath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.mozilla.dom.FileSystemGetFilesParams.domPath)
}

// required bool recursiveFlag = 4;
inline bool FileSystemGetFilesParams::_internal_has_recursiveflag() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool FileSystemGetFilesParams::has_recursiveflag() const {
  return _internal_has_recursiveflag();
}
inline void FileSystemGetFilesParams::clear_recursiveflag() {
  _impl_.recursiveflag_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool FileSystemGetFilesParams::_internal_recursiveflag() const {
  return _impl_.recursiveflag_;
}
inline bool FileSystemGetFilesParams::recursiveflag() const {
  // @@protoc_insertion_point(field_get:protobuf.mozilla.dom.FileSystemGetFilesParams.recursiveFlag)
  return _internal_recursiveflag();
}
inline void FileSystemGetFilesParams::_internal_set_recursiveflag(bool value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.recursiveflag_ = value;
}
inline void FileSystemGetFilesParams::set_recursiveflag(bool value) {
  _internal_set_recursiveflag(value);
  // @@protoc_insertion_point(field_set:protobuf.mozilla.dom.FileSystemGetFilesParams.recursiveFlag)
}

// -------------------------------------------------------------------

// FileSystemGetFileOrDirectoryParams

// required string filesystem = 1;
inline bool FileSystemGetFileOrDirectoryParams::_internal_has_filesystem() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool FileSystemGetFileOrDirectoryParams::has_filesystem() const {
  return _internal_has_filesystem();
}
inline void FileSystemGetFileOrDirectoryParams::clear_filesystem() {
  _impl_.filesystem_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& FileSystemGetFileOrDirectoryParams::filesystem() const {
  // @@protoc_insertion_point(field_get:protobuf.mozilla.dom.FileSystemGetFileOrDirectoryParams.filesystem)
  return _internal_filesystem();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileSystemGetFileOrDirectoryParams::set_filesystem(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.filesystem_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.mozilla.dom.FileSystemGetFileOrDirectoryParams.filesystem)
}
inline std::string* FileSystemGetFileOrDirectoryParams::mutable_filesystem() {
  std::string* _s = _internal_mutable_filesystem();
  // @@protoc_insertion_point(field_mutable:protobuf.mozilla.dom.FileSystemGetFileOrDirectoryParams.filesystem)
  return _s;
}
inline const std::string& FileSystemGetFileOrDirectoryParams::_internal_filesystem() const {
  return _impl_.filesystem_.Get();
}
inline void FileSystemGetFileOrDirectoryParams::_internal_set_filesystem(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.filesystem_.Set(value, GetArenaForAllocation());
}
inline std::string* FileSystemGetFileOrDirectoryParams::_internal_mutable_filesystem() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.filesystem_.Mutable(GetArenaForAllocation());
}
inline std::string* FileSystemGetFileOrDirectoryParams::release_filesystem() {
  // @@protoc_insertion_point(field_release:protobuf.mozilla.dom.FileSystemGetFileOrDirectoryParams.filesystem)
  if (!_internal_has_filesystem()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.filesystem_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filesystem_.IsDefault()) {
    _impl_.filesystem_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void FileSystemGetFileOrDirectoryParams::set_allocated_filesystem(std::string* filesystem) {
  if (filesystem != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.filesystem_.SetAllocated(filesystem, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filesystem_.IsDefault()) {
    _impl_.filesystem_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.mozilla.dom.FileSystemGetFileOrDirectoryParams.filesystem)
}

// required string realPath = 2;
inline bool FileSystemGetFileOrDirectoryParams::_internal_has_realpath() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool FileSystemGetFileOrDirectoryParams::has_realpath() const {
  return _internal_has_realpath();
}
inline void FileSystemGetFileOrDirectoryParams::clear_realpath() {
  _impl_.realpath_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& FileSystemGetFileOrDirectoryParams::realpath() const {
  // @@protoc_insertion_point(field_get:protobuf.mozilla.dom.FileSystemGetFileOrDirectoryParams.realPath)
  return _internal_realpath();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileSystemGetFileOrDirectoryParams::set_realpath(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.realpath_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.mozilla.dom.FileSystemGetFileOrDirectoryParams.realPath)
}
inline std::string* FileSystemGetFileOrDirectoryParams::mutable_realpath() {
  std::string* _s = _internal_mutable_realpath();
  // @@protoc_insertion_point(field_mutable:protobuf.mozilla.dom.FileSystemGetFileOrDirectoryParams.realPath)
  return _s;
}
inline const std::string& FileSystemGetFileOrDirectoryParams::_internal_realpath() const {
  return _impl_.realpath_.Get();
}
inline void FileSystemGetFileOrDirectoryParams::_internal_set_realpath(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.realpath_.Set(value, GetArenaForAllocation());
}
inline std::string* FileSystemGetFileOrDirectoryParams::_internal_mutable_realpath() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.realpath_.Mutable(GetArenaForAllocation());
}
inline std::string* FileSystemGetFileOrDirectoryParams::release_realpath() {
  // @@protoc_insertion_point(field_release:protobuf.mozilla.dom.FileSystemGetFileOrDirectoryParams.realPath)
  if (!_internal_has_realpath()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.realpath_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.realpath_.IsDefault()) {
    _impl_.realpath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void FileSystemGetFileOrDirectoryParams::set_allocated_realpath(std::string* realpath) {
  if (realpath != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.realpath_.SetAllocated(realpath, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.realpath_.IsDefault()) {
    _impl_.realpath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.mozilla.dom.FileSystemGetFileOrDirectoryParams.realPath)
}

// -------------------------------------------------------------------

// FileSystemParams

// .protobuf.mozilla.dom.FileSystemGetDirectoryListingParams mVFileSystemGetDirectoryListingParams = 1;
inline bool FileSystemParams::_internal_has_mvfilesystemgetdirectorylistingparams() const {
  return content_case() == kMVFileSystemGetDirectoryListingParams;
}
inline bool FileSystemParams::has_mvfilesystemgetdirectorylistingparams() const {
  return _internal_has_mvfilesystemgetdirectorylistingparams();
}
inline void FileSystemParams::set_has_mvfilesystemgetdirectorylistingparams() {
  _impl_._oneof_case_[0] = kMVFileSystemGetDirectoryListingParams;
}
inline void FileSystemParams::clear_mvfilesystemgetdirectorylistingparams() {
  if (_internal_has_mvfilesystemgetdirectorylistingparams()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.mvfilesystemgetdirectorylistingparams_;
    }
    clear_has_content();
  }
}
inline ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams* FileSystemParams::release_mvfilesystemgetdirectorylistingparams() {
  // @@protoc_insertion_point(field_release:protobuf.mozilla.dom.FileSystemParams.mVFileSystemGetDirectoryListingParams)
  if (_internal_has_mvfilesystemgetdirectorylistingparams()) {
    clear_has_content();
    ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams* temp = _impl_.content_.mvfilesystemgetdirectorylistingparams_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.mvfilesystemgetdirectorylistingparams_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams& FileSystemParams::_internal_mvfilesystemgetdirectorylistingparams() const {
  return _internal_has_mvfilesystemgetdirectorylistingparams()
      ? *_impl_.content_.mvfilesystemgetdirectorylistingparams_
      : reinterpret_cast< ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams&>(::protobuf::mozilla::dom::_FileSystemGetDirectoryListingParams_default_instance_);
}
inline const ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams& FileSystemParams::mvfilesystemgetdirectorylistingparams() const {
  // @@protoc_insertion_point(field_get:protobuf.mozilla.dom.FileSystemParams.mVFileSystemGetDirectoryListingParams)
  return _internal_mvfilesystemgetdirectorylistingparams();
}
inline ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams* FileSystemParams::unsafe_arena_release_mvfilesystemgetdirectorylistingparams() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protobuf.mozilla.dom.FileSystemParams.mVFileSystemGetDirectoryListingParams)
  if (_internal_has_mvfilesystemgetdirectorylistingparams()) {
    clear_has_content();
    ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams* temp = _impl_.content_.mvfilesystemgetdirectorylistingparams_;
    _impl_.content_.mvfilesystemgetdirectorylistingparams_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void FileSystemParams::unsafe_arena_set_allocated_mvfilesystemgetdirectorylistingparams(::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams* mvfilesystemgetdirectorylistingparams) {
  clear_content();
  if (mvfilesystemgetdirectorylistingparams) {
    set_has_mvfilesystemgetdirectorylistingparams();
    _impl_.content_.mvfilesystemgetdirectorylistingparams_ = mvfilesystemgetdirectorylistingparams;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.mozilla.dom.FileSystemParams.mVFileSystemGetDirectoryListingParams)
}
inline ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams* FileSystemParams::_internal_mutable_mvfilesystemgetdirectorylistingparams() {
  if (!_internal_has_mvfilesystemgetdirectorylistingparams()) {
    clear_content();
    set_has_mvfilesystemgetdirectorylistingparams();
    _impl_.content_.mvfilesystemgetdirectorylistingparams_ = CreateMaybeMessage< ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams >(GetArenaForAllocation());
  }
  return _impl_.content_.mvfilesystemgetdirectorylistingparams_;
}
inline ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams* FileSystemParams::mutable_mvfilesystemgetdirectorylistingparams() {
  ::protobuf::mozilla::dom::FileSystemGetDirectoryListingParams* _msg = _internal_mutable_mvfilesystemgetdirectorylistingparams();
  // @@protoc_insertion_point(field_mutable:protobuf.mozilla.dom.FileSystemParams.mVFileSystemGetDirectoryListingParams)
  return _msg;
}

// .protobuf.mozilla.dom.FileSystemGetFilesParams mVFileSystemGetFilesParams = 2;
inline bool FileSystemParams::_internal_has_mvfilesystemgetfilesparams() const {
  return content_case() == kMVFileSystemGetFilesParams;
}
inline bool FileSystemParams::has_mvfilesystemgetfilesparams() const {
  return _internal_has_mvfilesystemgetfilesparams();
}
inline void FileSystemParams::set_has_mvfilesystemgetfilesparams() {
  _impl_._oneof_case_[0] = kMVFileSystemGetFilesParams;
}
inline void FileSystemParams::clear_mvfilesystemgetfilesparams() {
  if (_internal_has_mvfilesystemgetfilesparams()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.mvfilesystemgetfilesparams_;
    }
    clear_has_content();
  }
}
inline ::protobuf::mozilla::dom::FileSystemGetFilesParams* FileSystemParams::release_mvfilesystemgetfilesparams() {
  // @@protoc_insertion_point(field_release:protobuf.mozilla.dom.FileSystemParams.mVFileSystemGetFilesParams)
  if (_internal_has_mvfilesystemgetfilesparams()) {
    clear_has_content();
    ::protobuf::mozilla::dom::FileSystemGetFilesParams* temp = _impl_.content_.mvfilesystemgetfilesparams_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.mvfilesystemgetfilesparams_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::protobuf::mozilla::dom::FileSystemGetFilesParams& FileSystemParams::_internal_mvfilesystemgetfilesparams() const {
  return _internal_has_mvfilesystemgetfilesparams()
      ? *_impl_.content_.mvfilesystemgetfilesparams_
      : reinterpret_cast< ::protobuf::mozilla::dom::FileSystemGetFilesParams&>(::protobuf::mozilla::dom::_FileSystemGetFilesParams_default_instance_);
}
inline const ::protobuf::mozilla::dom::FileSystemGetFilesParams& FileSystemParams::mvfilesystemgetfilesparams() const {
  // @@protoc_insertion_point(field_get:protobuf.mozilla.dom.FileSystemParams.mVFileSystemGetFilesParams)
  return _internal_mvfilesystemgetfilesparams();
}
inline ::protobuf::mozilla::dom::FileSystemGetFilesParams* FileSystemParams::unsafe_arena_release_mvfilesystemgetfilesparams() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protobuf.mozilla.dom.FileSystemParams.mVFileSystemGetFilesParams)
  if (_internal_has_mvfilesystemgetfilesparams()) {
    clear_has_content();
    ::protobuf::mozilla::dom::FileSystemGetFilesParams* temp = _impl_.content_.mvfilesystemgetfilesparams_;
    _impl_.content_.mvfilesystemgetfilesparams_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void FileSystemParams::unsafe_arena_set_allocated_mvfilesystemgetfilesparams(::protobuf::mozilla::dom::FileSystemGetFilesParams* mvfilesystemgetfilesparams) {
  clear_content();
  if (mvfilesystemgetfilesparams) {
    set_has_mvfilesystemgetfilesparams();
    _impl_.content_.mvfilesystemgetfilesparams_ = mvfilesystemgetfilesparams;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.mozilla.dom.FileSystemParams.mVFileSystemGetFilesParams)
}
inline ::protobuf::mozilla::dom::FileSystemGetFilesParams* FileSystemParams::_internal_mutable_mvfilesystemgetfilesparams() {
  if (!_internal_has_mvfilesystemgetfilesparams()) {
    clear_content();
    set_has_mvfilesystemgetfilesparams();
    _impl_.content_.mvfilesystemgetfilesparams_ = CreateMaybeMessage< ::protobuf::mozilla::dom::FileSystemGetFilesParams >(GetArenaForAllocation());
  }
  return _impl_.content_.mvfilesystemgetfilesparams_;
}
inline ::protobuf::mozilla::dom::FileSystemGetFilesParams* FileSystemParams::mutable_mvfilesystemgetfilesparams() {
  ::protobuf::mozilla::dom::FileSystemGetFilesParams* _msg = _internal_mutable_mvfilesystemgetfilesparams();
  // @@protoc_insertion_point(field_mutable:protobuf.mozilla.dom.FileSystemParams.mVFileSystemGetFilesParams)
  return _msg;
}

// .protobuf.mozilla.dom.FileSystemGetFileOrDirectoryParams mVFileSystemGetFileOrDirectoryParams = 3;
inline bool FileSystemParams::_internal_has_mvfilesystemgetfileordirectoryparams() const {
  return content_case() == kMVFileSystemGetFileOrDirectoryParams;
}
inline bool FileSystemParams::has_mvfilesystemgetfileordirectoryparams() const {
  return _internal_has_mvfilesystemgetfileordirectoryparams();
}
inline void FileSystemParams::set_has_mvfilesystemgetfileordirectoryparams() {
  _impl_._oneof_case_[0] = kMVFileSystemGetFileOrDirectoryParams;
}
inline void FileSystemParams::clear_mvfilesystemgetfileordirectoryparams() {
  if (_internal_has_mvfilesystemgetfileordirectoryparams()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.mvfilesystemgetfileordirectoryparams_;
    }
    clear_has_content();
  }
}
inline ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams* FileSystemParams::release_mvfilesystemgetfileordirectoryparams() {
  // @@protoc_insertion_point(field_release:protobuf.mozilla.dom.FileSystemParams.mVFileSystemGetFileOrDirectoryParams)
  if (_internal_has_mvfilesystemgetfileordirectoryparams()) {
    clear_has_content();
    ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams* temp = _impl_.content_.mvfilesystemgetfileordirectoryparams_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.mvfilesystemgetfileordirectoryparams_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams& FileSystemParams::_internal_mvfilesystemgetfileordirectoryparams() const {
  return _internal_has_mvfilesystemgetfileordirectoryparams()
      ? *_impl_.content_.mvfilesystemgetfileordirectoryparams_
      : reinterpret_cast< ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams&>(::protobuf::mozilla::dom::_FileSystemGetFileOrDirectoryParams_default_instance_);
}
inline const ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams& FileSystemParams::mvfilesystemgetfileordirectoryparams() const {
  // @@protoc_insertion_point(field_get:protobuf.mozilla.dom.FileSystemParams.mVFileSystemGetFileOrDirectoryParams)
  return _internal_mvfilesystemgetfileordirectoryparams();
}
inline ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams* FileSystemParams::unsafe_arena_release_mvfilesystemgetfileordirectoryparams() {
  // @@protoc_insertion_point(field_unsafe_arena_release:protobuf.mozilla.dom.FileSystemParams.mVFileSystemGetFileOrDirectoryParams)
  if (_internal_has_mvfilesystemgetfileordirectoryparams()) {
    clear_has_content();
    ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams* temp = _impl_.content_.mvfilesystemgetfileordirectoryparams_;
    _impl_.content_.mvfilesystemgetfileordirectoryparams_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void FileSystemParams::unsafe_arena_set_allocated_mvfilesystemgetfileordirectoryparams(::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams* mvfilesystemgetfileordirectoryparams) {
  clear_content();
  if (mvfilesystemgetfileordirectoryparams) {
    set_has_mvfilesystemgetfileordirectoryparams();
    _impl_.content_.mvfilesystemgetfileordirectoryparams_ = mvfilesystemgetfileordirectoryparams;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.mozilla.dom.FileSystemParams.mVFileSystemGetFileOrDirectoryParams)
}
inline ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams* FileSystemParams::_internal_mutable_mvfilesystemgetfileordirectoryparams() {
  if (!_internal_has_mvfilesystemgetfileordirectoryparams()) {
    clear_content();
    set_has_mvfilesystemgetfileordirectoryparams();
    _impl_.content_.mvfilesystemgetfileordirectoryparams_ = CreateMaybeMessage< ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams >(GetArenaForAllocation());
  }
  return _impl_.content_.mvfilesystemgetfileordirectoryparams_;
}
inline ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams* FileSystemParams::mutable_mvfilesystemgetfileordirectoryparams() {
  ::protobuf::mozilla::dom::FileSystemGetFileOrDirectoryParams* _msg = _internal_mutable_mvfilesystemgetfileordirectoryparams();
  // @@protoc_insertion_point(field_mutable:protobuf.mozilla.dom.FileSystemParams.mVFileSystemGetFileOrDirectoryParams)
  return _msg;
}

inline bool FileSystemParams::has_content() const {
  return content_case() != CONTENT_NOT_SET;
}
inline void FileSystemParams::clear_has_content() {
  _impl_._oneof_case_[0] = CONTENT_NOT_SET;
}
inline FileSystemParams::ContentCase FileSystemParams::content_case() const {
  return FileSystemParams::ContentCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace dom
}  // namespace mozilla
}  // namespace protobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_PFileSystemParams_5fprotobuf_2emozilla_2edom_2eh_2eproto
