// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PLockManager_protobuf.mozilla.dom.locks.h.proto

#include "PLockManager_protobuf.mozilla.dom.locks.h.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace protobuf {
namespace mozilla {
namespace dom {
namespace locks {
PROTOBUF_CONSTEXPR IPCLockRequest::IPCLockRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.a_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.a_lockmode_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.a_ifavailable_)*/false
  , /*decltype(_impl_.a_steal_)*/false} {}
struct IPCLockRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IPCLockRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~IPCLockRequestDefaultTypeInternal() {}
  union {
    IPCLockRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IPCLockRequestDefaultTypeInternal _IPCLockRequest_default_instance_;
}  // namespace locks
}  // namespace dom
}  // namespace mozilla
}  // namespace protobuf
namespace protobuf {
namespace mozilla {
namespace dom {
namespace locks {

// ===================================================================

class IPCLockRequest::_Internal {
 public:
  using HasBits = decltype(std::declval<IPCLockRequest>()._impl_._has_bits_);
  static void set_has_a_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_a_lockmode(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_a_ifavailable(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_a_steal(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x0000000f) ^ 0x0000000f) != 0;
  }
};

IPCLockRequest::IPCLockRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla.dom.locks.IPCLockRequest)
}
IPCLockRequest::IPCLockRequest(const IPCLockRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  IPCLockRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.a_name_){}
    , decltype(_impl_.a_lockmode_){}
    , decltype(_impl_.a_ifavailable_){}
    , decltype(_impl_.a_steal_){}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _impl_.a_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_a_name()) {
    _this->_impl_.a_name_.Set(from._internal_a_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.a_lockmode_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_lockmode_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_a_lockmode()) {
    _this->_impl_.a_lockmode_.Set(from._internal_a_lockmode(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.a_ifavailable_, &from._impl_.a_ifavailable_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.a_steal_) -
    reinterpret_cast<char*>(&_impl_.a_ifavailable_)) + sizeof(_impl_.a_steal_));
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla.dom.locks.IPCLockRequest)
}

inline void IPCLockRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.a_name_){}
    , decltype(_impl_.a_lockmode_){}
    , decltype(_impl_.a_ifavailable_){false}
    , decltype(_impl_.a_steal_){false}
  };
  _impl_.a_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.a_lockmode_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_lockmode_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

IPCLockRequest::~IPCLockRequest() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla.dom.locks.IPCLockRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void IPCLockRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.a_name_.Destroy();
  _impl_.a_lockmode_.Destroy();
}

void IPCLockRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void IPCLockRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla.dom.locks.IPCLockRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.a_name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.a_lockmode_.ClearNonDefaultToEmpty();
    }
  }
  ::memset(&_impl_.a_ifavailable_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.a_steal_) -
      reinterpret_cast<char*>(&_impl_.a_ifavailable_)) + sizeof(_impl_.a_steal_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* IPCLockRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required string a_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_a_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required bytes a_lockMode = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_a_lockmode();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required bool a_ifAvailable = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_a_ifavailable(&has_bits);
          _impl_.a_ifavailable_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required bool a_steal = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_a_steal(&has_bits);
          _impl_.a_steal_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* IPCLockRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla.dom.locks.IPCLockRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required string a_name = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_a_name(), target);
  }

  // required bytes a_lockMode = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_a_lockmode(), target);
  }

  // required bool a_ifAvailable = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_a_ifavailable(), target);
  }

  // required bool a_steal = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_a_steal(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla.dom.locks.IPCLockRequest)
  return target;
}

size_t IPCLockRequest::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:protobuf.mozilla.dom.locks.IPCLockRequest)
  size_t total_size = 0;

  if (_internal_has_a_name()) {
    // required string a_name = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_a_name());
  }

  if (_internal_has_a_lockmode()) {
    // required bytes a_lockMode = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_lockmode());
  }

  if (_internal_has_a_ifavailable()) {
    // required bool a_ifAvailable = 3;
    total_size += 1 + 1;
  }

  if (_internal_has_a_steal()) {
    // required bool a_steal = 4;
    total_size += 1 + 1;
  }

  return total_size;
}
size_t IPCLockRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla.dom.locks.IPCLockRequest)
  size_t total_size = 0;

  if (((_impl_._has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required string a_name = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_a_name());

    // required bytes a_lockMode = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_lockmode());

    // required bool a_ifAvailable = 3;
    total_size += 1 + 1;

    // required bool a_steal = 4;
    total_size += 1 + 1;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void IPCLockRequest::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const IPCLockRequest*>(
      &from));
}

void IPCLockRequest::MergeFrom(const IPCLockRequest& from) {
  IPCLockRequest* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla.dom.locks.IPCLockRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_a_name(from._internal_a_name());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_a_lockmode(from._internal_a_lockmode());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.a_ifavailable_ = from._impl_.a_ifavailable_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.a_steal_ = from._impl_.a_steal_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void IPCLockRequest::CopyFrom(const IPCLockRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla.dom.locks.IPCLockRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IPCLockRequest::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void IPCLockRequest::InternalSwap(IPCLockRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_name_, lhs_arena,
      &other->_impl_.a_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_lockmode_, lhs_arena,
      &other->_impl_.a_lockmode_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(IPCLockRequest, _impl_.a_steal_)
      + sizeof(IPCLockRequest::_impl_.a_steal_)
      - PROTOBUF_FIELD_OFFSET(IPCLockRequest, _impl_.a_ifavailable_)>(
          reinterpret_cast<char*>(&_impl_.a_ifavailable_),
          reinterpret_cast<char*>(&other->_impl_.a_ifavailable_));
}

std::string IPCLockRequest::GetTypeName() const {
  return "protobuf.mozilla.dom.locks.IPCLockRequest";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace locks
}  // namespace dom
}  // namespace mozilla
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::dom::locks::IPCLockRequest*
Arena::CreateMaybeMessage< ::protobuf::mozilla::dom::locks::IPCLockRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::dom::locks::IPCLockRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
