// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PStunAddrsRequest.proto

#include "PStunAddrsRequest.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace protobuf {
namespace mozilla {
namespace net {
namespace PStunAddrsRequest {
PROTOBUF_CONSTEXPR Msg_GetStunAddrs::Msg_GetStunAddrs(
    ::_pbi::ConstantInitialized) {}
struct Msg_GetStunAddrsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Msg_GetStunAddrsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Msg_GetStunAddrsDefaultTypeInternal() {}
  union {
    Msg_GetStunAddrs _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Msg_GetStunAddrsDefaultTypeInternal _Msg_GetStunAddrs_default_instance_;
PROTOBUF_CONSTEXPR Msg_RegisterMDNSHostname::Msg_RegisterMDNSHostname(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.a_hostname_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.a_address_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Msg_RegisterMDNSHostnameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Msg_RegisterMDNSHostnameDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Msg_RegisterMDNSHostnameDefaultTypeInternal() {}
  union {
    Msg_RegisterMDNSHostname _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Msg_RegisterMDNSHostnameDefaultTypeInternal _Msg_RegisterMDNSHostname_default_instance_;
PROTOBUF_CONSTEXPR Msg_QueryMDNSHostname::Msg_QueryMDNSHostname(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.a_hostname_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Msg_QueryMDNSHostnameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Msg_QueryMDNSHostnameDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Msg_QueryMDNSHostnameDefaultTypeInternal() {}
  union {
    Msg_QueryMDNSHostname _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Msg_QueryMDNSHostnameDefaultTypeInternal _Msg_QueryMDNSHostname_default_instance_;
PROTOBUF_CONSTEXPR Msg_UnregisterMDNSHostname::Msg_UnregisterMDNSHostname(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.a_hostname_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Msg_UnregisterMDNSHostnameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Msg_UnregisterMDNSHostnameDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Msg_UnregisterMDNSHostnameDefaultTypeInternal() {}
  union {
    Msg_UnregisterMDNSHostname _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Msg_UnregisterMDNSHostnameDefaultTypeInternal _Msg_UnregisterMDNSHostname_default_instance_;
PROTOBUF_CONSTEXPR Msg___delete__::Msg___delete__(
    ::_pbi::ConstantInitialized) {}
struct Msg___delete__DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Msg___delete__DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Msg___delete__DefaultTypeInternal() {}
  union {
    Msg___delete__ _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Msg___delete__DefaultTypeInternal _Msg___delete___default_instance_;
PROTOBUF_CONSTEXPR Reply___delete__::Reply___delete__(
    ::_pbi::ConstantInitialized) {}
struct Reply___delete__DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Reply___delete__DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Reply___delete__DefaultTypeInternal() {}
  union {
    Reply___delete__ _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Reply___delete__DefaultTypeInternal _Reply___delete___default_instance_;
PROTOBUF_CONSTEXPR Msg_OnMDNSQueryComplete::Msg_OnMDNSQueryComplete(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.a_hostname_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.a_address_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Msg_OnMDNSQueryCompleteDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Msg_OnMDNSQueryCompleteDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Msg_OnMDNSQueryCompleteDefaultTypeInternal() {}
  union {
    Msg_OnMDNSQueryComplete _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Msg_OnMDNSQueryCompleteDefaultTypeInternal _Msg_OnMDNSQueryComplete_default_instance_;
PROTOBUF_CONSTEXPR Msg_OnStunAddrsAvailable::Msg_OnStunAddrsAvailable(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.a_icestunaddrs_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Msg_OnStunAddrsAvailableDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Msg_OnStunAddrsAvailableDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Msg_OnStunAddrsAvailableDefaultTypeInternal() {}
  union {
    Msg_OnStunAddrsAvailable _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Msg_OnStunAddrsAvailableDefaultTypeInternal _Msg_OnStunAddrsAvailable_default_instance_;
}  // namespace PStunAddrsRequest
}  // namespace net
}  // namespace mozilla
}  // namespace protobuf
static ::_pb::Metadata file_level_metadata_PStunAddrsRequest_2eproto[8];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_PStunAddrsRequest_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_PStunAddrsRequest_2eproto = nullptr;

const uint32_t TableStruct_PStunAddrsRequest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::net::PStunAddrsRequest::Msg_GetStunAddrs, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::net::PStunAddrsRequest::Msg_RegisterMDNSHostname, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::net::PStunAddrsRequest::Msg_RegisterMDNSHostname, _impl_.a_hostname_),
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::net::PStunAddrsRequest::Msg_RegisterMDNSHostname, _impl_.a_address_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::net::PStunAddrsRequest::Msg_QueryMDNSHostname, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::net::PStunAddrsRequest::Msg_QueryMDNSHostname, _impl_.a_hostname_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::net::PStunAddrsRequest::Msg_UnregisterMDNSHostname, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::net::PStunAddrsRequest::Msg_UnregisterMDNSHostname, _impl_.a_hostname_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::net::PStunAddrsRequest::Msg___delete__, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::net::PStunAddrsRequest::Reply___delete__, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::net::PStunAddrsRequest::Msg_OnMDNSQueryComplete, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::net::PStunAddrsRequest::Msg_OnMDNSQueryComplete, _impl_.a_hostname_),
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::net::PStunAddrsRequest::Msg_OnMDNSQueryComplete, _impl_.a_address_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::net::PStunAddrsRequest::Msg_OnStunAddrsAvailable, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::net::PStunAddrsRequest::Msg_OnStunAddrsAvailable, _impl_.a_icestunaddrs_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::protobuf::mozilla::net::PStunAddrsRequest::Msg_GetStunAddrs)},
  { 6, -1, -1, sizeof(::protobuf::mozilla::net::PStunAddrsRequest::Msg_RegisterMDNSHostname)},
  { 14, -1, -1, sizeof(::protobuf::mozilla::net::PStunAddrsRequest::Msg_QueryMDNSHostname)},
  { 21, -1, -1, sizeof(::protobuf::mozilla::net::PStunAddrsRequest::Msg_UnregisterMDNSHostname)},
  { 28, -1, -1, sizeof(::protobuf::mozilla::net::PStunAddrsRequest::Msg___delete__)},
  { 34, -1, -1, sizeof(::protobuf::mozilla::net::PStunAddrsRequest::Reply___delete__)},
  { 40, -1, -1, sizeof(::protobuf::mozilla::net::PStunAddrsRequest::Msg_OnMDNSQueryComplete)},
  { 48, -1, -1, sizeof(::protobuf::mozilla::net::PStunAddrsRequest::Msg_OnStunAddrsAvailable)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::protobuf::mozilla::net::PStunAddrsRequest::_Msg_GetStunAddrs_default_instance_._instance,
  &::protobuf::mozilla::net::PStunAddrsRequest::_Msg_RegisterMDNSHostname_default_instance_._instance,
  &::protobuf::mozilla::net::PStunAddrsRequest::_Msg_QueryMDNSHostname_default_instance_._instance,
  &::protobuf::mozilla::net::PStunAddrsRequest::_Msg_UnregisterMDNSHostname_default_instance_._instance,
  &::protobuf::mozilla::net::PStunAddrsRequest::_Msg___delete___default_instance_._instance,
  &::protobuf::mozilla::net::PStunAddrsRequest::_Reply___delete___default_instance_._instance,
  &::protobuf::mozilla::net::PStunAddrsRequest::_Msg_OnMDNSQueryComplete_default_instance_._instance,
  &::protobuf::mozilla::net::PStunAddrsRequest::_Msg_OnStunAddrsAvailable_default_instance_._instance,
};

const char descriptor_table_protodef_PStunAddrsRequest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027PStunAddrsRequest.proto\022&protobuf.mozi"
  "lla.net.PStunAddrsRequest\"\022\n\020Msg_GetStun"
  "Addrs\"A\n\030Msg_RegisterMDNSHostname\022\022\n\na_h"
  "ostname\030\001 \001(\t\022\021\n\ta_address\030\002 \001(\t\"+\n\025Msg_"
  "QueryMDNSHostname\022\022\n\na_hostname\030\001 \001(\t\"0\n"
  "\032Msg_UnregisterMDNSHostname\022\022\n\na_hostnam"
  "e\030\001 \001(\t\"\020\n\016Msg___delete__\"\022\n\020Reply___del"
  "ete__\"@\n\027Msg_OnMDNSQueryComplete\022\022\n\na_ho"
  "stname\030\001 \001(\t\022\021\n\ta_address\030\002 \001(\014\"2\n\030Msg_O"
  "nStunAddrsAvailable\022\026\n\016a_iceStunAddrs\030\001 "
  "\001(\014b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_PStunAddrsRequest_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_PStunAddrsRequest_2eproto = {
    false, false, 411, descriptor_table_protodef_PStunAddrsRequest_2eproto,
    "PStunAddrsRequest.proto",
    &descriptor_table_PStunAddrsRequest_2eproto_once, nullptr, 0, 8,
    schemas, file_default_instances, TableStruct_PStunAddrsRequest_2eproto::offsets,
    file_level_metadata_PStunAddrsRequest_2eproto, file_level_enum_descriptors_PStunAddrsRequest_2eproto,
    file_level_service_descriptors_PStunAddrsRequest_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_PStunAddrsRequest_2eproto_getter() {
  return &descriptor_table_PStunAddrsRequest_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_PStunAddrsRequest_2eproto(&descriptor_table_PStunAddrsRequest_2eproto);
namespace protobuf {
namespace mozilla {
namespace net {
namespace PStunAddrsRequest {

// ===================================================================

class Msg_GetStunAddrs::_Internal {
 public:
};

Msg_GetStunAddrs::Msg_GetStunAddrs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla.net.PStunAddrsRequest.Msg_GetStunAddrs)
}
Msg_GetStunAddrs::Msg_GetStunAddrs(const Msg_GetStunAddrs& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  Msg_GetStunAddrs* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla.net.PStunAddrsRequest.Msg_GetStunAddrs)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Msg_GetStunAddrs::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Msg_GetStunAddrs::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Msg_GetStunAddrs::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PStunAddrsRequest_2eproto_getter, &descriptor_table_PStunAddrsRequest_2eproto_once,
      file_level_metadata_PStunAddrsRequest_2eproto[0]);
}

// ===================================================================

class Msg_RegisterMDNSHostname::_Internal {
 public:
};

Msg_RegisterMDNSHostname::Msg_RegisterMDNSHostname(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla.net.PStunAddrsRequest.Msg_RegisterMDNSHostname)
}
Msg_RegisterMDNSHostname::Msg_RegisterMDNSHostname(const Msg_RegisterMDNSHostname& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Msg_RegisterMDNSHostname* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.a_hostname_){}
    , decltype(_impl_.a_address_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.a_hostname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_hostname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_a_hostname().empty()) {
    _this->_impl_.a_hostname_.Set(from._internal_a_hostname(), 
      _this->GetArenaForAllocation());
  }
  _impl_.a_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_a_address().empty()) {
    _this->_impl_.a_address_.Set(from._internal_a_address(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla.net.PStunAddrsRequest.Msg_RegisterMDNSHostname)
}

inline void Msg_RegisterMDNSHostname::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.a_hostname_){}
    , decltype(_impl_.a_address_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.a_hostname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_hostname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.a_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Msg_RegisterMDNSHostname::~Msg_RegisterMDNSHostname() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla.net.PStunAddrsRequest.Msg_RegisterMDNSHostname)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Msg_RegisterMDNSHostname::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.a_hostname_.Destroy();
  _impl_.a_address_.Destroy();
}

void Msg_RegisterMDNSHostname::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Msg_RegisterMDNSHostname::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_RegisterMDNSHostname)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.a_hostname_.ClearToEmpty();
  _impl_.a_address_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Msg_RegisterMDNSHostname::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string a_hostname = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_a_hostname();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.mozilla.net.PStunAddrsRequest.Msg_RegisterMDNSHostname.a_hostname"));
        } else
          goto handle_unusual;
        continue;
      // string a_address = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_a_address();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.mozilla.net.PStunAddrsRequest.Msg_RegisterMDNSHostname.a_address"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Msg_RegisterMDNSHostname::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_RegisterMDNSHostname)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string a_hostname = 1;
  if (!this->_internal_a_hostname().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_a_hostname().data(), static_cast<int>(this->_internal_a_hostname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.mozilla.net.PStunAddrsRequest.Msg_RegisterMDNSHostname.a_hostname");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_a_hostname(), target);
  }

  // string a_address = 2;
  if (!this->_internal_a_address().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_a_address().data(), static_cast<int>(this->_internal_a_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.mozilla.net.PStunAddrsRequest.Msg_RegisterMDNSHostname.a_address");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_a_address(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla.net.PStunAddrsRequest.Msg_RegisterMDNSHostname)
  return target;
}

size_t Msg_RegisterMDNSHostname::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_RegisterMDNSHostname)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string a_hostname = 1;
  if (!this->_internal_a_hostname().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_a_hostname());
  }

  // string a_address = 2;
  if (!this->_internal_a_address().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_a_address());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Msg_RegisterMDNSHostname::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Msg_RegisterMDNSHostname::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Msg_RegisterMDNSHostname::GetClassData() const { return &_class_data_; }


void Msg_RegisterMDNSHostname::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Msg_RegisterMDNSHostname*>(&to_msg);
  auto& from = static_cast<const Msg_RegisterMDNSHostname&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_RegisterMDNSHostname)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_a_hostname().empty()) {
    _this->_internal_set_a_hostname(from._internal_a_hostname());
  }
  if (!from._internal_a_address().empty()) {
    _this->_internal_set_a_address(from._internal_a_address());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Msg_RegisterMDNSHostname::CopyFrom(const Msg_RegisterMDNSHostname& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_RegisterMDNSHostname)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_RegisterMDNSHostname::IsInitialized() const {
  return true;
}

void Msg_RegisterMDNSHostname::InternalSwap(Msg_RegisterMDNSHostname* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_hostname_, lhs_arena,
      &other->_impl_.a_hostname_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_address_, lhs_arena,
      &other->_impl_.a_address_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Msg_RegisterMDNSHostname::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PStunAddrsRequest_2eproto_getter, &descriptor_table_PStunAddrsRequest_2eproto_once,
      file_level_metadata_PStunAddrsRequest_2eproto[1]);
}

// ===================================================================

class Msg_QueryMDNSHostname::_Internal {
 public:
};

Msg_QueryMDNSHostname::Msg_QueryMDNSHostname(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla.net.PStunAddrsRequest.Msg_QueryMDNSHostname)
}
Msg_QueryMDNSHostname::Msg_QueryMDNSHostname(const Msg_QueryMDNSHostname& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Msg_QueryMDNSHostname* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.a_hostname_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.a_hostname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_hostname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_a_hostname().empty()) {
    _this->_impl_.a_hostname_.Set(from._internal_a_hostname(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla.net.PStunAddrsRequest.Msg_QueryMDNSHostname)
}

inline void Msg_QueryMDNSHostname::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.a_hostname_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.a_hostname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_hostname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Msg_QueryMDNSHostname::~Msg_QueryMDNSHostname() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla.net.PStunAddrsRequest.Msg_QueryMDNSHostname)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Msg_QueryMDNSHostname::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.a_hostname_.Destroy();
}

void Msg_QueryMDNSHostname::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Msg_QueryMDNSHostname::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_QueryMDNSHostname)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.a_hostname_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Msg_QueryMDNSHostname::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string a_hostname = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_a_hostname();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.mozilla.net.PStunAddrsRequest.Msg_QueryMDNSHostname.a_hostname"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Msg_QueryMDNSHostname::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_QueryMDNSHostname)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string a_hostname = 1;
  if (!this->_internal_a_hostname().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_a_hostname().data(), static_cast<int>(this->_internal_a_hostname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.mozilla.net.PStunAddrsRequest.Msg_QueryMDNSHostname.a_hostname");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_a_hostname(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla.net.PStunAddrsRequest.Msg_QueryMDNSHostname)
  return target;
}

size_t Msg_QueryMDNSHostname::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_QueryMDNSHostname)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string a_hostname = 1;
  if (!this->_internal_a_hostname().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_a_hostname());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Msg_QueryMDNSHostname::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Msg_QueryMDNSHostname::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Msg_QueryMDNSHostname::GetClassData() const { return &_class_data_; }


void Msg_QueryMDNSHostname::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Msg_QueryMDNSHostname*>(&to_msg);
  auto& from = static_cast<const Msg_QueryMDNSHostname&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_QueryMDNSHostname)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_a_hostname().empty()) {
    _this->_internal_set_a_hostname(from._internal_a_hostname());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Msg_QueryMDNSHostname::CopyFrom(const Msg_QueryMDNSHostname& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_QueryMDNSHostname)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_QueryMDNSHostname::IsInitialized() const {
  return true;
}

void Msg_QueryMDNSHostname::InternalSwap(Msg_QueryMDNSHostname* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_hostname_, lhs_arena,
      &other->_impl_.a_hostname_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Msg_QueryMDNSHostname::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PStunAddrsRequest_2eproto_getter, &descriptor_table_PStunAddrsRequest_2eproto_once,
      file_level_metadata_PStunAddrsRequest_2eproto[2]);
}

// ===================================================================

class Msg_UnregisterMDNSHostname::_Internal {
 public:
};

Msg_UnregisterMDNSHostname::Msg_UnregisterMDNSHostname(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla.net.PStunAddrsRequest.Msg_UnregisterMDNSHostname)
}
Msg_UnregisterMDNSHostname::Msg_UnregisterMDNSHostname(const Msg_UnregisterMDNSHostname& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Msg_UnregisterMDNSHostname* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.a_hostname_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.a_hostname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_hostname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_a_hostname().empty()) {
    _this->_impl_.a_hostname_.Set(from._internal_a_hostname(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla.net.PStunAddrsRequest.Msg_UnregisterMDNSHostname)
}

inline void Msg_UnregisterMDNSHostname::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.a_hostname_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.a_hostname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_hostname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Msg_UnregisterMDNSHostname::~Msg_UnregisterMDNSHostname() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla.net.PStunAddrsRequest.Msg_UnregisterMDNSHostname)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Msg_UnregisterMDNSHostname::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.a_hostname_.Destroy();
}

void Msg_UnregisterMDNSHostname::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Msg_UnregisterMDNSHostname::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_UnregisterMDNSHostname)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.a_hostname_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Msg_UnregisterMDNSHostname::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string a_hostname = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_a_hostname();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.mozilla.net.PStunAddrsRequest.Msg_UnregisterMDNSHostname.a_hostname"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Msg_UnregisterMDNSHostname::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_UnregisterMDNSHostname)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string a_hostname = 1;
  if (!this->_internal_a_hostname().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_a_hostname().data(), static_cast<int>(this->_internal_a_hostname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.mozilla.net.PStunAddrsRequest.Msg_UnregisterMDNSHostname.a_hostname");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_a_hostname(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla.net.PStunAddrsRequest.Msg_UnregisterMDNSHostname)
  return target;
}

size_t Msg_UnregisterMDNSHostname::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_UnregisterMDNSHostname)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string a_hostname = 1;
  if (!this->_internal_a_hostname().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_a_hostname());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Msg_UnregisterMDNSHostname::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Msg_UnregisterMDNSHostname::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Msg_UnregisterMDNSHostname::GetClassData() const { return &_class_data_; }


void Msg_UnregisterMDNSHostname::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Msg_UnregisterMDNSHostname*>(&to_msg);
  auto& from = static_cast<const Msg_UnregisterMDNSHostname&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_UnregisterMDNSHostname)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_a_hostname().empty()) {
    _this->_internal_set_a_hostname(from._internal_a_hostname());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Msg_UnregisterMDNSHostname::CopyFrom(const Msg_UnregisterMDNSHostname& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_UnregisterMDNSHostname)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_UnregisterMDNSHostname::IsInitialized() const {
  return true;
}

void Msg_UnregisterMDNSHostname::InternalSwap(Msg_UnregisterMDNSHostname* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_hostname_, lhs_arena,
      &other->_impl_.a_hostname_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Msg_UnregisterMDNSHostname::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PStunAddrsRequest_2eproto_getter, &descriptor_table_PStunAddrsRequest_2eproto_once,
      file_level_metadata_PStunAddrsRequest_2eproto[3]);
}

// ===================================================================

class Msg___delete__::_Internal {
 public:
};

Msg___delete__::Msg___delete__(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla.net.PStunAddrsRequest.Msg___delete__)
}
Msg___delete__::Msg___delete__(const Msg___delete__& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  Msg___delete__* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla.net.PStunAddrsRequest.Msg___delete__)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Msg___delete__::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Msg___delete__::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Msg___delete__::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PStunAddrsRequest_2eproto_getter, &descriptor_table_PStunAddrsRequest_2eproto_once,
      file_level_metadata_PStunAddrsRequest_2eproto[4]);
}

// ===================================================================

class Reply___delete__::_Internal {
 public:
};

Reply___delete__::Reply___delete__(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla.net.PStunAddrsRequest.Reply___delete__)
}
Reply___delete__::Reply___delete__(const Reply___delete__& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  Reply___delete__* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla.net.PStunAddrsRequest.Reply___delete__)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Reply___delete__::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Reply___delete__::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Reply___delete__::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PStunAddrsRequest_2eproto_getter, &descriptor_table_PStunAddrsRequest_2eproto_once,
      file_level_metadata_PStunAddrsRequest_2eproto[5]);
}

// ===================================================================

class Msg_OnMDNSQueryComplete::_Internal {
 public:
};

Msg_OnMDNSQueryComplete::Msg_OnMDNSQueryComplete(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnMDNSQueryComplete)
}
Msg_OnMDNSQueryComplete::Msg_OnMDNSQueryComplete(const Msg_OnMDNSQueryComplete& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Msg_OnMDNSQueryComplete* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.a_hostname_){}
    , decltype(_impl_.a_address_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.a_hostname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_hostname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_a_hostname().empty()) {
    _this->_impl_.a_hostname_.Set(from._internal_a_hostname(), 
      _this->GetArenaForAllocation());
  }
  _impl_.a_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_a_address().empty()) {
    _this->_impl_.a_address_.Set(from._internal_a_address(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnMDNSQueryComplete)
}

inline void Msg_OnMDNSQueryComplete::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.a_hostname_){}
    , decltype(_impl_.a_address_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.a_hostname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_hostname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.a_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Msg_OnMDNSQueryComplete::~Msg_OnMDNSQueryComplete() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnMDNSQueryComplete)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Msg_OnMDNSQueryComplete::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.a_hostname_.Destroy();
  _impl_.a_address_.Destroy();
}

void Msg_OnMDNSQueryComplete::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Msg_OnMDNSQueryComplete::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnMDNSQueryComplete)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.a_hostname_.ClearToEmpty();
  _impl_.a_address_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Msg_OnMDNSQueryComplete::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string a_hostname = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_a_hostname();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.mozilla.net.PStunAddrsRequest.Msg_OnMDNSQueryComplete.a_hostname"));
        } else
          goto handle_unusual;
        continue;
      // bytes a_address = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_a_address();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Msg_OnMDNSQueryComplete::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnMDNSQueryComplete)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string a_hostname = 1;
  if (!this->_internal_a_hostname().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_a_hostname().data(), static_cast<int>(this->_internal_a_hostname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf.mozilla.net.PStunAddrsRequest.Msg_OnMDNSQueryComplete.a_hostname");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_a_hostname(), target);
  }

  // bytes a_address = 2;
  if (!this->_internal_a_address().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_a_address(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnMDNSQueryComplete)
  return target;
}

size_t Msg_OnMDNSQueryComplete::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnMDNSQueryComplete)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string a_hostname = 1;
  if (!this->_internal_a_hostname().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_a_hostname());
  }

  // bytes a_address = 2;
  if (!this->_internal_a_address().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_address());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Msg_OnMDNSQueryComplete::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Msg_OnMDNSQueryComplete::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Msg_OnMDNSQueryComplete::GetClassData() const { return &_class_data_; }


void Msg_OnMDNSQueryComplete::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Msg_OnMDNSQueryComplete*>(&to_msg);
  auto& from = static_cast<const Msg_OnMDNSQueryComplete&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnMDNSQueryComplete)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_a_hostname().empty()) {
    _this->_internal_set_a_hostname(from._internal_a_hostname());
  }
  if (!from._internal_a_address().empty()) {
    _this->_internal_set_a_address(from._internal_a_address());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Msg_OnMDNSQueryComplete::CopyFrom(const Msg_OnMDNSQueryComplete& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnMDNSQueryComplete)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_OnMDNSQueryComplete::IsInitialized() const {
  return true;
}

void Msg_OnMDNSQueryComplete::InternalSwap(Msg_OnMDNSQueryComplete* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_hostname_, lhs_arena,
      &other->_impl_.a_hostname_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_address_, lhs_arena,
      &other->_impl_.a_address_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Msg_OnMDNSQueryComplete::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PStunAddrsRequest_2eproto_getter, &descriptor_table_PStunAddrsRequest_2eproto_once,
      file_level_metadata_PStunAddrsRequest_2eproto[6]);
}

// ===================================================================

class Msg_OnStunAddrsAvailable::_Internal {
 public:
};

Msg_OnStunAddrsAvailable::Msg_OnStunAddrsAvailable(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnStunAddrsAvailable)
}
Msg_OnStunAddrsAvailable::Msg_OnStunAddrsAvailable(const Msg_OnStunAddrsAvailable& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Msg_OnStunAddrsAvailable* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.a_icestunaddrs_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.a_icestunaddrs_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_icestunaddrs_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_a_icestunaddrs().empty()) {
    _this->_impl_.a_icestunaddrs_.Set(from._internal_a_icestunaddrs(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnStunAddrsAvailable)
}

inline void Msg_OnStunAddrsAvailable::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.a_icestunaddrs_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.a_icestunaddrs_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_icestunaddrs_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Msg_OnStunAddrsAvailable::~Msg_OnStunAddrsAvailable() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnStunAddrsAvailable)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Msg_OnStunAddrsAvailable::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.a_icestunaddrs_.Destroy();
}

void Msg_OnStunAddrsAvailable::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Msg_OnStunAddrsAvailable::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnStunAddrsAvailable)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.a_icestunaddrs_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Msg_OnStunAddrsAvailable::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes a_iceStunAddrs = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_a_icestunaddrs();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Msg_OnStunAddrsAvailable::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnStunAddrsAvailable)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes a_iceStunAddrs = 1;
  if (!this->_internal_a_icestunaddrs().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_a_icestunaddrs(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnStunAddrsAvailable)
  return target;
}

size_t Msg_OnStunAddrsAvailable::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnStunAddrsAvailable)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes a_iceStunAddrs = 1;
  if (!this->_internal_a_icestunaddrs().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_a_icestunaddrs());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Msg_OnStunAddrsAvailable::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Msg_OnStunAddrsAvailable::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Msg_OnStunAddrsAvailable::GetClassData() const { return &_class_data_; }


void Msg_OnStunAddrsAvailable::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Msg_OnStunAddrsAvailable*>(&to_msg);
  auto& from = static_cast<const Msg_OnStunAddrsAvailable&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnStunAddrsAvailable)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_a_icestunaddrs().empty()) {
    _this->_internal_set_a_icestunaddrs(from._internal_a_icestunaddrs());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Msg_OnStunAddrsAvailable::CopyFrom(const Msg_OnStunAddrsAvailable& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla.net.PStunAddrsRequest.Msg_OnStunAddrsAvailable)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_OnStunAddrsAvailable::IsInitialized() const {
  return true;
}

void Msg_OnStunAddrsAvailable::InternalSwap(Msg_OnStunAddrsAvailable* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_icestunaddrs_, lhs_arena,
      &other->_impl_.a_icestunaddrs_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Msg_OnStunAddrsAvailable::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PStunAddrsRequest_2eproto_getter, &descriptor_table_PStunAddrsRequest_2eproto_once,
      file_level_metadata_PStunAddrsRequest_2eproto[7]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace PStunAddrsRequest
}  // namespace net
}  // namespace mozilla
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::net::PStunAddrsRequest::Msg_GetStunAddrs*
Arena::CreateMaybeMessage< ::protobuf::mozilla::net::PStunAddrsRequest::Msg_GetStunAddrs >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::net::PStunAddrsRequest::Msg_GetStunAddrs >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::net::PStunAddrsRequest::Msg_RegisterMDNSHostname*
Arena::CreateMaybeMessage< ::protobuf::mozilla::net::PStunAddrsRequest::Msg_RegisterMDNSHostname >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::net::PStunAddrsRequest::Msg_RegisterMDNSHostname >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::net::PStunAddrsRequest::Msg_QueryMDNSHostname*
Arena::CreateMaybeMessage< ::protobuf::mozilla::net::PStunAddrsRequest::Msg_QueryMDNSHostname >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::net::PStunAddrsRequest::Msg_QueryMDNSHostname >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::net::PStunAddrsRequest::Msg_UnregisterMDNSHostname*
Arena::CreateMaybeMessage< ::protobuf::mozilla::net::PStunAddrsRequest::Msg_UnregisterMDNSHostname >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::net::PStunAddrsRequest::Msg_UnregisterMDNSHostname >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::net::PStunAddrsRequest::Msg___delete__*
Arena::CreateMaybeMessage< ::protobuf::mozilla::net::PStunAddrsRequest::Msg___delete__ >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::net::PStunAddrsRequest::Msg___delete__ >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::net::PStunAddrsRequest::Reply___delete__*
Arena::CreateMaybeMessage< ::protobuf::mozilla::net::PStunAddrsRequest::Reply___delete__ >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::net::PStunAddrsRequest::Reply___delete__ >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::net::PStunAddrsRequest::Msg_OnMDNSQueryComplete*
Arena::CreateMaybeMessage< ::protobuf::mozilla::net::PStunAddrsRequest::Msg_OnMDNSQueryComplete >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::net::PStunAddrsRequest::Msg_OnMDNSQueryComplete >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::net::PStunAddrsRequest::Msg_OnStunAddrsAvailable*
Arena::CreateMaybeMessage< ::protobuf::mozilla::net::PStunAddrsRequest::Msg_OnStunAddrsAvailable >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::net::PStunAddrsRequest::Msg_OnStunAddrsAvailable >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
