// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PTemporaryIPCBlob_protobuf.mozilla.dom.h.proto

#include "PTemporaryIPCBlob_protobuf.mozilla.dom.h.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace protobuf {
namespace mozilla {
namespace dom {
PROTOBUF_CONSTEXPR IPCBlobOrError::IPCBlobOrError(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.content_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct IPCBlobOrErrorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IPCBlobOrErrorDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~IPCBlobOrErrorDefaultTypeInternal() {}
  union {
    IPCBlobOrError _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IPCBlobOrErrorDefaultTypeInternal _IPCBlobOrError_default_instance_;
}  // namespace dom
}  // namespace mozilla
}  // namespace protobuf
static ::_pb::Metadata file_level_metadata_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto = nullptr;

const uint32_t TableStruct_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::dom::IPCBlobOrError, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::dom::IPCBlobOrError, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::protobuf::mozilla::dom::IPCBlobOrError, _impl_.content_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::protobuf::mozilla::dom::IPCBlobOrError)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::protobuf::mozilla::dom::_IPCBlobOrError_default_instance_._instance,
};

const char descriptor_table_protodef_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n.PTemporaryIPCBlob_protobuf.mozilla.dom"
  ".h.proto\022\024protobuf.mozilla.dom\032\rIPCBlob."
  "proto\"i\n\016IPCBlobOrError\0224\n\013a_mVIPCBlob\030\001"
  " \001(\0132\035.protobuf.mozilla.dom.IPCBlobH\000\022\026\n"
  "\014a_mVnsresult\030\002 \001(\014H\000B\t\n\007contentb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto_deps[1] = {
  &::descriptor_table_IPCBlob_2eproto,
};
static ::_pbi::once_flag descriptor_table_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto = {
    false, false, 200, descriptor_table_protodef_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto,
    "PTemporaryIPCBlob_protobuf.mozilla.dom.h.proto",
    &descriptor_table_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto_once, descriptor_table_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto::offsets,
    file_level_metadata_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto, file_level_enum_descriptors_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto,
    file_level_service_descriptors_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto_getter() {
  return &descriptor_table_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto(&descriptor_table_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto);
namespace protobuf {
namespace mozilla {
namespace dom {

// ===================================================================

class IPCBlobOrError::_Internal {
 public:
  static const ::protobuf::mozilla::dom::IPCBlob& a_mvipcblob(const IPCBlobOrError* msg);
};

const ::protobuf::mozilla::dom::IPCBlob&
IPCBlobOrError::_Internal::a_mvipcblob(const IPCBlobOrError* msg) {
  return *msg->_impl_.content_.a_mvipcblob_;
}
void IPCBlobOrError::set_allocated_a_mvipcblob(::protobuf::mozilla::dom::IPCBlob* a_mvipcblob) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_content();
  if (a_mvipcblob) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(a_mvipcblob));
    if (message_arena != submessage_arena) {
      a_mvipcblob = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, a_mvipcblob, submessage_arena);
    }
    set_has_a_mvipcblob();
    _impl_.content_.a_mvipcblob_ = a_mvipcblob;
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.mozilla.dom.IPCBlobOrError.a_mVIPCBlob)
}
void IPCBlobOrError::clear_a_mvipcblob() {
  if (_internal_has_a_mvipcblob()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.a_mvipcblob_;
    }
    clear_has_content();
  }
}
IPCBlobOrError::IPCBlobOrError(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla.dom.IPCBlobOrError)
}
IPCBlobOrError::IPCBlobOrError(const IPCBlobOrError& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  IPCBlobOrError* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.content_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_content();
  switch (from.content_case()) {
    case kAMVIPCBlob: {
      _this->_internal_mutable_a_mvipcblob()->::protobuf::mozilla::dom::IPCBlob::MergeFrom(
          from._internal_a_mvipcblob());
      break;
    }
    case kAMVnsresult: {
      _this->_internal_set_a_mvnsresult(from._internal_a_mvnsresult());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla.dom.IPCBlobOrError)
}

inline void IPCBlobOrError::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.content_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_content();
}

IPCBlobOrError::~IPCBlobOrError() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla.dom.IPCBlobOrError)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void IPCBlobOrError::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_content()) {
    clear_content();
  }
}

void IPCBlobOrError::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void IPCBlobOrError::clear_content() {
// @@protoc_insertion_point(one_of_clear_start:protobuf.mozilla.dom.IPCBlobOrError)
  switch (content_case()) {
    case kAMVIPCBlob: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.content_.a_mvipcblob_;
      }
      break;
    }
    case kAMVnsresult: {
      _impl_.content_.a_mvnsresult_.Destroy();
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = CONTENT_NOT_SET;
}


void IPCBlobOrError::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla.dom.IPCBlobOrError)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_content();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* IPCBlobOrError::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .protobuf.mozilla.dom.IPCBlob a_mVIPCBlob = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_a_mvipcblob(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes a_mVnsresult = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_a_mvnsresult();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* IPCBlobOrError::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla.dom.IPCBlobOrError)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .protobuf.mozilla.dom.IPCBlob a_mVIPCBlob = 1;
  if (_internal_has_a_mvipcblob()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::a_mvipcblob(this),
        _Internal::a_mvipcblob(this).GetCachedSize(), target, stream);
  }

  // bytes a_mVnsresult = 2;
  if (_internal_has_a_mvnsresult()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_a_mvnsresult(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla.dom.IPCBlobOrError)
  return target;
}

size_t IPCBlobOrError::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla.dom.IPCBlobOrError)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (content_case()) {
    // .protobuf.mozilla.dom.IPCBlob a_mVIPCBlob = 1;
    case kAMVIPCBlob: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.content_.a_mvipcblob_);
      break;
    }
    // bytes a_mVnsresult = 2;
    case kAMVnsresult: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_a_mvnsresult());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData IPCBlobOrError::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    IPCBlobOrError::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*IPCBlobOrError::GetClassData() const { return &_class_data_; }


void IPCBlobOrError::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<IPCBlobOrError*>(&to_msg);
  auto& from = static_cast<const IPCBlobOrError&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla.dom.IPCBlobOrError)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.content_case()) {
    case kAMVIPCBlob: {
      _this->_internal_mutable_a_mvipcblob()->::protobuf::mozilla::dom::IPCBlob::MergeFrom(
          from._internal_a_mvipcblob());
      break;
    }
    case kAMVnsresult: {
      _this->_internal_set_a_mvnsresult(from._internal_a_mvnsresult());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void IPCBlobOrError::CopyFrom(const IPCBlobOrError& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla.dom.IPCBlobOrError)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IPCBlobOrError::IsInitialized() const {
  return true;
}

void IPCBlobOrError::InternalSwap(IPCBlobOrError* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.content_, other->_impl_.content_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata IPCBlobOrError::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto_getter, &descriptor_table_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto_once,
      file_level_metadata_PTemporaryIPCBlob_5fprotobuf_2emozilla_2edom_2eh_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace dom
}  // namespace mozilla
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::dom::IPCBlobOrError*
Arena::CreateMaybeMessage< ::protobuf::mozilla::dom::IPCBlobOrError >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::dom::IPCBlobOrError >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
