// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PTestJSON.proto

#include "PTestJSON.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace protobuf {
namespace mozilla {
namespace _ipdltest {
namespace PTestJSON {
PROTOBUF_CONSTEXPR Msg_Start::Msg_Start(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._cached_size_)*/{}} {}
struct Msg_StartDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Msg_StartDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Msg_StartDefaultTypeInternal() {}
  union {
    Msg_Start _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Msg_StartDefaultTypeInternal _Msg_Start_default_instance_;
PROTOBUF_CONSTEXPR Msg_PTestJSONHandleConstructor::Msg_PTestJSONHandleConstructor(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._cached_size_)*/{}} {}
struct Msg_PTestJSONHandleConstructorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Msg_PTestJSONHandleConstructorDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Msg_PTestJSONHandleConstructorDefaultTypeInternal() {}
  union {
    Msg_PTestJSONHandleConstructor _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Msg_PTestJSONHandleConstructorDefaultTypeInternal _Msg_PTestJSONHandleConstructor_default_instance_;
PROTOBUF_CONSTEXPR Reply_PTestJSONHandleConstructor::Reply_PTestJSONHandleConstructor(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._cached_size_)*/{}} {}
struct Reply_PTestJSONHandleConstructorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Reply_PTestJSONHandleConstructorDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Reply_PTestJSONHandleConstructorDefaultTypeInternal() {}
  union {
    Reply_PTestJSONHandleConstructor _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Reply_PTestJSONHandleConstructorDefaultTypeInternal _Reply_PTestJSONHandleConstructor_default_instance_;
PROTOBUF_CONSTEXPR Msg_Test::Msg_Test(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.i_)*/nullptr} {}
struct Msg_TestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Msg_TestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Msg_TestDefaultTypeInternal() {}
  union {
    Msg_Test _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Msg_TestDefaultTypeInternal _Msg_Test_default_instance_;
PROTOBUF_CONSTEXPR Reply_Test::Reply_Test(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.o_)*/nullptr} {}
struct Reply_TestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Reply_TestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Reply_TestDefaultTypeInternal() {}
  union {
    Reply_Test _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Reply_TestDefaultTypeInternal _Reply_Test_default_instance_;
PROTOBUF_CONSTEXPR Msg___delete__::Msg___delete__(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._cached_size_)*/{}} {}
struct Msg___delete__DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Msg___delete__DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Msg___delete__DefaultTypeInternal() {}
  union {
    Msg___delete__ _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Msg___delete__DefaultTypeInternal _Msg___delete___default_instance_;
PROTOBUF_CONSTEXPR Reply___delete__::Reply___delete__(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._cached_size_)*/{}} {}
struct Reply___delete__DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Reply___delete__DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Reply___delete__DefaultTypeInternal() {}
  union {
    Reply___delete__ _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Reply___delete__DefaultTypeInternal _Reply___delete___default_instance_;
}  // namespace PTestJSON
}  // namespace _ipdltest
}  // namespace mozilla
}  // namespace protobuf
namespace protobuf {
namespace mozilla {
namespace _ipdltest {
namespace PTestJSON {

// ===================================================================

class Msg_Start::_Internal {
 public:
};

Msg_Start::Msg_Start(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla._ipdltest.PTestJSON.Msg_Start)
}
Msg_Start::Msg_Start(const Msg_Start& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  Msg_Start* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla._ipdltest.PTestJSON.Msg_Start)
}

inline void Msg_Start::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_._cached_size_)*/{}
  };
}

Msg_Start::~Msg_Start() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla._ipdltest.PTestJSON.Msg_Start)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Msg_Start::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Msg_Start::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Msg_Start::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla._ipdltest.PTestJSON.Msg_Start)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<std::string>();
}

const char* Msg_Start::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Msg_Start::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla._ipdltest.PTestJSON.Msg_Start)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla._ipdltest.PTestJSON.Msg_Start)
  return target;
}

size_t Msg_Start::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla._ipdltest.PTestJSON.Msg_Start)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Msg_Start::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Msg_Start*>(
      &from));
}

void Msg_Start::MergeFrom(const Msg_Start& from) {
  Msg_Start* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla._ipdltest.PTestJSON.Msg_Start)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Msg_Start::CopyFrom(const Msg_Start& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla._ipdltest.PTestJSON.Msg_Start)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_Start::IsInitialized() const {
  return true;
}

void Msg_Start::InternalSwap(Msg_Start* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
}

std::string Msg_Start::GetTypeName() const {
  return "protobuf.mozilla._ipdltest.PTestJSON.Msg_Start";
}


// ===================================================================

class Msg_PTestJSONHandleConstructor::_Internal {
 public:
};

Msg_PTestJSONHandleConstructor::Msg_PTestJSONHandleConstructor(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla._ipdltest.PTestJSON.Msg_PTestJSONHandleConstructor)
}
Msg_PTestJSONHandleConstructor::Msg_PTestJSONHandleConstructor(const Msg_PTestJSONHandleConstructor& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  Msg_PTestJSONHandleConstructor* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla._ipdltest.PTestJSON.Msg_PTestJSONHandleConstructor)
}

inline void Msg_PTestJSONHandleConstructor::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_._cached_size_)*/{}
  };
}

Msg_PTestJSONHandleConstructor::~Msg_PTestJSONHandleConstructor() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla._ipdltest.PTestJSON.Msg_PTestJSONHandleConstructor)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Msg_PTestJSONHandleConstructor::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Msg_PTestJSONHandleConstructor::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Msg_PTestJSONHandleConstructor::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla._ipdltest.PTestJSON.Msg_PTestJSONHandleConstructor)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<std::string>();
}

const char* Msg_PTestJSONHandleConstructor::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Msg_PTestJSONHandleConstructor::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla._ipdltest.PTestJSON.Msg_PTestJSONHandleConstructor)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla._ipdltest.PTestJSON.Msg_PTestJSONHandleConstructor)
  return target;
}

size_t Msg_PTestJSONHandleConstructor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla._ipdltest.PTestJSON.Msg_PTestJSONHandleConstructor)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Msg_PTestJSONHandleConstructor::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Msg_PTestJSONHandleConstructor*>(
      &from));
}

void Msg_PTestJSONHandleConstructor::MergeFrom(const Msg_PTestJSONHandleConstructor& from) {
  Msg_PTestJSONHandleConstructor* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla._ipdltest.PTestJSON.Msg_PTestJSONHandleConstructor)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Msg_PTestJSONHandleConstructor::CopyFrom(const Msg_PTestJSONHandleConstructor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla._ipdltest.PTestJSON.Msg_PTestJSONHandleConstructor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_PTestJSONHandleConstructor::IsInitialized() const {
  return true;
}

void Msg_PTestJSONHandleConstructor::InternalSwap(Msg_PTestJSONHandleConstructor* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
}

std::string Msg_PTestJSONHandleConstructor::GetTypeName() const {
  return "protobuf.mozilla._ipdltest.PTestJSON.Msg_PTestJSONHandleConstructor";
}


// ===================================================================

class Reply_PTestJSONHandleConstructor::_Internal {
 public:
};

Reply_PTestJSONHandleConstructor::Reply_PTestJSONHandleConstructor(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla._ipdltest.PTestJSON.Reply_PTestJSONHandleConstructor)
}
Reply_PTestJSONHandleConstructor::Reply_PTestJSONHandleConstructor(const Reply_PTestJSONHandleConstructor& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  Reply_PTestJSONHandleConstructor* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla._ipdltest.PTestJSON.Reply_PTestJSONHandleConstructor)
}

inline void Reply_PTestJSONHandleConstructor::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_._cached_size_)*/{}
  };
}

Reply_PTestJSONHandleConstructor::~Reply_PTestJSONHandleConstructor() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla._ipdltest.PTestJSON.Reply_PTestJSONHandleConstructor)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Reply_PTestJSONHandleConstructor::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Reply_PTestJSONHandleConstructor::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Reply_PTestJSONHandleConstructor::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla._ipdltest.PTestJSON.Reply_PTestJSONHandleConstructor)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<std::string>();
}

const char* Reply_PTestJSONHandleConstructor::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Reply_PTestJSONHandleConstructor::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla._ipdltest.PTestJSON.Reply_PTestJSONHandleConstructor)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla._ipdltest.PTestJSON.Reply_PTestJSONHandleConstructor)
  return target;
}

size_t Reply_PTestJSONHandleConstructor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla._ipdltest.PTestJSON.Reply_PTestJSONHandleConstructor)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Reply_PTestJSONHandleConstructor::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Reply_PTestJSONHandleConstructor*>(
      &from));
}

void Reply_PTestJSONHandleConstructor::MergeFrom(const Reply_PTestJSONHandleConstructor& from) {
  Reply_PTestJSONHandleConstructor* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla._ipdltest.PTestJSON.Reply_PTestJSONHandleConstructor)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Reply_PTestJSONHandleConstructor::CopyFrom(const Reply_PTestJSONHandleConstructor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla._ipdltest.PTestJSON.Reply_PTestJSONHandleConstructor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Reply_PTestJSONHandleConstructor::IsInitialized() const {
  return true;
}

void Reply_PTestJSONHandleConstructor::InternalSwap(Reply_PTestJSONHandleConstructor* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
}

std::string Reply_PTestJSONHandleConstructor::GetTypeName() const {
  return "protobuf.mozilla._ipdltest.PTestJSON.Reply_PTestJSONHandleConstructor";
}


// ===================================================================

class Msg_Test::_Internal {
 public:
  using HasBits = decltype(std::declval<Msg_Test>()._impl_._has_bits_);
  static const ::protobuf::mozilla::_ipdltest::JSONVariant& i(const Msg_Test* msg);
  static void set_has_i(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

const ::protobuf::mozilla::_ipdltest::JSONVariant&
Msg_Test::_Internal::i(const Msg_Test* msg) {
  return *msg->_impl_.i_;
}
void Msg_Test::clear_i() {
  if (_impl_.i_ != nullptr) _impl_.i_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
Msg_Test::Msg_Test(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla._ipdltest.PTestJSON.Msg_Test)
}
Msg_Test::Msg_Test(const Msg_Test& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  Msg_Test* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.i_){nullptr}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  if (from._internal_has_i()) {
    _this->_impl_.i_ = new ::protobuf::mozilla::_ipdltest::JSONVariant(*from._impl_.i_);
  }
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla._ipdltest.PTestJSON.Msg_Test)
}

inline void Msg_Test::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.i_){nullptr}
  };
}

Msg_Test::~Msg_Test() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla._ipdltest.PTestJSON.Msg_Test)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Msg_Test::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.i_;
}

void Msg_Test::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Msg_Test::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla._ipdltest.PTestJSON.Msg_Test)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(_impl_.i_ != nullptr);
    _impl_.i_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* Msg_Test::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required .protobuf.mozilla._ipdltest.JSONVariant i = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_i(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Msg_Test::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla._ipdltest.PTestJSON.Msg_Test)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required .protobuf.mozilla._ipdltest.JSONVariant i = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::i(this),
        _Internal::i(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla._ipdltest.PTestJSON.Msg_Test)
  return target;
}

size_t Msg_Test::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla._ipdltest.PTestJSON.Msg_Test)
  size_t total_size = 0;

  // required .protobuf.mozilla._ipdltest.JSONVariant i = 1;
  if (_internal_has_i()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.i_);
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Msg_Test::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Msg_Test*>(
      &from));
}

void Msg_Test::MergeFrom(const Msg_Test& from) {
  Msg_Test* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla._ipdltest.PTestJSON.Msg_Test)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_i()) {
    _this->_internal_mutable_i()->::protobuf::mozilla::_ipdltest::JSONVariant::MergeFrom(
        from._internal_i());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Msg_Test::CopyFrom(const Msg_Test& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla._ipdltest.PTestJSON.Msg_Test)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_Test::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  if (_internal_has_i()) {
    if (!_impl_.i_->IsInitialized()) return false;
  }
  return true;
}

void Msg_Test::InternalSwap(Msg_Test* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.i_, other->_impl_.i_);
}

std::string Msg_Test::GetTypeName() const {
  return "protobuf.mozilla._ipdltest.PTestJSON.Msg_Test";
}


// ===================================================================

class Reply_Test::_Internal {
 public:
  using HasBits = decltype(std::declval<Reply_Test>()._impl_._has_bits_);
  static const ::protobuf::mozilla::_ipdltest::JSONVariant& o(const Reply_Test* msg);
  static void set_has_o(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

const ::protobuf::mozilla::_ipdltest::JSONVariant&
Reply_Test::_Internal::o(const Reply_Test* msg) {
  return *msg->_impl_.o_;
}
void Reply_Test::clear_o() {
  if (_impl_.o_ != nullptr) _impl_.o_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
Reply_Test::Reply_Test(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla._ipdltest.PTestJSON.Reply_Test)
}
Reply_Test::Reply_Test(const Reply_Test& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  Reply_Test* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.o_){nullptr}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  if (from._internal_has_o()) {
    _this->_impl_.o_ = new ::protobuf::mozilla::_ipdltest::JSONVariant(*from._impl_.o_);
  }
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla._ipdltest.PTestJSON.Reply_Test)
}

inline void Reply_Test::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.o_){nullptr}
  };
}

Reply_Test::~Reply_Test() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla._ipdltest.PTestJSON.Reply_Test)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Reply_Test::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.o_;
}

void Reply_Test::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Reply_Test::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla._ipdltest.PTestJSON.Reply_Test)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(_impl_.o_ != nullptr);
    _impl_.o_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* Reply_Test::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required .protobuf.mozilla._ipdltest.JSONVariant o = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_o(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Reply_Test::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla._ipdltest.PTestJSON.Reply_Test)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required .protobuf.mozilla._ipdltest.JSONVariant o = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::o(this),
        _Internal::o(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla._ipdltest.PTestJSON.Reply_Test)
  return target;
}

size_t Reply_Test::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla._ipdltest.PTestJSON.Reply_Test)
  size_t total_size = 0;

  // required .protobuf.mozilla._ipdltest.JSONVariant o = 1;
  if (_internal_has_o()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.o_);
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Reply_Test::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Reply_Test*>(
      &from));
}

void Reply_Test::MergeFrom(const Reply_Test& from) {
  Reply_Test* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla._ipdltest.PTestJSON.Reply_Test)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_o()) {
    _this->_internal_mutable_o()->::protobuf::mozilla::_ipdltest::JSONVariant::MergeFrom(
        from._internal_o());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Reply_Test::CopyFrom(const Reply_Test& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla._ipdltest.PTestJSON.Reply_Test)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Reply_Test::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  if (_internal_has_o()) {
    if (!_impl_.o_->IsInitialized()) return false;
  }
  return true;
}

void Reply_Test::InternalSwap(Reply_Test* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.o_, other->_impl_.o_);
}

std::string Reply_Test::GetTypeName() const {
  return "protobuf.mozilla._ipdltest.PTestJSON.Reply_Test";
}


// ===================================================================

class Msg___delete__::_Internal {
 public:
};

Msg___delete__::Msg___delete__(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla._ipdltest.PTestJSON.Msg___delete__)
}
Msg___delete__::Msg___delete__(const Msg___delete__& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  Msg___delete__* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla._ipdltest.PTestJSON.Msg___delete__)
}

inline void Msg___delete__::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_._cached_size_)*/{}
  };
}

Msg___delete__::~Msg___delete__() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla._ipdltest.PTestJSON.Msg___delete__)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Msg___delete__::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Msg___delete__::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Msg___delete__::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla._ipdltest.PTestJSON.Msg___delete__)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<std::string>();
}

const char* Msg___delete__::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Msg___delete__::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla._ipdltest.PTestJSON.Msg___delete__)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla._ipdltest.PTestJSON.Msg___delete__)
  return target;
}

size_t Msg___delete__::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla._ipdltest.PTestJSON.Msg___delete__)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Msg___delete__::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Msg___delete__*>(
      &from));
}

void Msg___delete__::MergeFrom(const Msg___delete__& from) {
  Msg___delete__* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla._ipdltest.PTestJSON.Msg___delete__)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Msg___delete__::CopyFrom(const Msg___delete__& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla._ipdltest.PTestJSON.Msg___delete__)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg___delete__::IsInitialized() const {
  return true;
}

void Msg___delete__::InternalSwap(Msg___delete__* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
}

std::string Msg___delete__::GetTypeName() const {
  return "protobuf.mozilla._ipdltest.PTestJSON.Msg___delete__";
}


// ===================================================================

class Reply___delete__::_Internal {
 public:
};

Reply___delete__::Reply___delete__(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla._ipdltest.PTestJSON.Reply___delete__)
}
Reply___delete__::Reply___delete__(const Reply___delete__& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  Reply___delete__* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla._ipdltest.PTestJSON.Reply___delete__)
}

inline void Reply___delete__::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_._cached_size_)*/{}
  };
}

Reply___delete__::~Reply___delete__() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla._ipdltest.PTestJSON.Reply___delete__)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Reply___delete__::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Reply___delete__::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Reply___delete__::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla._ipdltest.PTestJSON.Reply___delete__)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<std::string>();
}

const char* Reply___delete__::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Reply___delete__::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla._ipdltest.PTestJSON.Reply___delete__)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla._ipdltest.PTestJSON.Reply___delete__)
  return target;
}

size_t Reply___delete__::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla._ipdltest.PTestJSON.Reply___delete__)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Reply___delete__::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Reply___delete__*>(
      &from));
}

void Reply___delete__::MergeFrom(const Reply___delete__& from) {
  Reply___delete__* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla._ipdltest.PTestJSON.Reply___delete__)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Reply___delete__::CopyFrom(const Reply___delete__& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla._ipdltest.PTestJSON.Reply___delete__)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Reply___delete__::IsInitialized() const {
  return true;
}

void Reply___delete__::InternalSwap(Reply___delete__* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
}

std::string Reply___delete__::GetTypeName() const {
  return "protobuf.mozilla._ipdltest.PTestJSON.Reply___delete__";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace PTestJSON
}  // namespace _ipdltest
}  // namespace mozilla
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::_ipdltest::PTestJSON::Msg_Start*
Arena::CreateMaybeMessage< ::protobuf::mozilla::_ipdltest::PTestJSON::Msg_Start >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::_ipdltest::PTestJSON::Msg_Start >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::_ipdltest::PTestJSON::Msg_PTestJSONHandleConstructor*
Arena::CreateMaybeMessage< ::protobuf::mozilla::_ipdltest::PTestJSON::Msg_PTestJSONHandleConstructor >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::_ipdltest::PTestJSON::Msg_PTestJSONHandleConstructor >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::_ipdltest::PTestJSON::Reply_PTestJSONHandleConstructor*
Arena::CreateMaybeMessage< ::protobuf::mozilla::_ipdltest::PTestJSON::Reply_PTestJSONHandleConstructor >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::_ipdltest::PTestJSON::Reply_PTestJSONHandleConstructor >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::_ipdltest::PTestJSON::Msg_Test*
Arena::CreateMaybeMessage< ::protobuf::mozilla::_ipdltest::PTestJSON::Msg_Test >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::_ipdltest::PTestJSON::Msg_Test >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::_ipdltest::PTestJSON::Reply_Test*
Arena::CreateMaybeMessage< ::protobuf::mozilla::_ipdltest::PTestJSON::Reply_Test >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::_ipdltest::PTestJSON::Reply_Test >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::_ipdltest::PTestJSON::Msg___delete__*
Arena::CreateMaybeMessage< ::protobuf::mozilla::_ipdltest::PTestJSON::Msg___delete__ >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::_ipdltest::PTestJSON::Msg___delete__ >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::_ipdltest::PTestJSON::Reply___delete__*
Arena::CreateMaybeMessage< ::protobuf::mozilla::_ipdltest::PTestJSON::Reply___delete__ >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::_ipdltest::PTestJSON::Reply___delete__ >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
