// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PTestDestroyNested.proto

#include "PTestDestroyNested.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace protobuf {
namespace mozilla {
namespace _ipdltest {
namespace PTestDestroyNested {
PROTOBUF_CONSTEXPR Msg_PTestDestroyNestedSubConstructor::Msg_PTestDestroyNestedSubConstructor(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.a_actorid_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Msg_PTestDestroyNestedSubConstructorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Msg_PTestDestroyNestedSubConstructorDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Msg_PTestDestroyNestedSubConstructorDefaultTypeInternal() {}
  union {
    Msg_PTestDestroyNestedSubConstructor _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Msg_PTestDestroyNestedSubConstructorDefaultTypeInternal _Msg_PTestDestroyNestedSubConstructor_default_instance_;
PROTOBUF_CONSTEXPR Reply_PTestDestroyNestedSubConstructor::Reply_PTestDestroyNestedSubConstructor(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._cached_size_)*/{}} {}
struct Reply_PTestDestroyNestedSubConstructorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Reply_PTestDestroyNestedSubConstructorDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Reply_PTestDestroyNestedSubConstructorDefaultTypeInternal() {}
  union {
    Reply_PTestDestroyNestedSubConstructor _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Reply_PTestDestroyNestedSubConstructorDefaultTypeInternal _Reply_PTestDestroyNestedSubConstructor_default_instance_;
}  // namespace PTestDestroyNested
}  // namespace _ipdltest
}  // namespace mozilla
}  // namespace protobuf
namespace protobuf {
namespace mozilla {
namespace _ipdltest {
namespace PTestDestroyNested {

// ===================================================================

class Msg_PTestDestroyNestedSubConstructor::_Internal {
 public:
};

Msg_PTestDestroyNestedSubConstructor::Msg_PTestDestroyNestedSubConstructor(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla._ipdltest.PTestDestroyNested.Msg_PTestDestroyNestedSubConstructor)
}
Msg_PTestDestroyNestedSubConstructor::Msg_PTestDestroyNestedSubConstructor(const Msg_PTestDestroyNestedSubConstructor& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  Msg_PTestDestroyNestedSubConstructor* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.a_actorid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _this->_impl_.a_actorid_ = from._impl_.a_actorid_;
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla._ipdltest.PTestDestroyNested.Msg_PTestDestroyNestedSubConstructor)
}

inline void Msg_PTestDestroyNestedSubConstructor::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.a_actorid_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Msg_PTestDestroyNestedSubConstructor::~Msg_PTestDestroyNestedSubConstructor() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla._ipdltest.PTestDestroyNested.Msg_PTestDestroyNestedSubConstructor)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Msg_PTestDestroyNestedSubConstructor::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Msg_PTestDestroyNestedSubConstructor::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Msg_PTestDestroyNestedSubConstructor::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla._ipdltest.PTestDestroyNested.Msg_PTestDestroyNestedSubConstructor)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.a_actorid_ = int64_t{0};
  _internal_metadata_.Clear<std::string>();
}

const char* Msg_PTestDestroyNestedSubConstructor::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // sint64 a_actorid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.a_actorid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Msg_PTestDestroyNestedSubConstructor::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla._ipdltest.PTestDestroyNested.Msg_PTestDestroyNestedSubConstructor)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // sint64 a_actorid = 1;
  if (this->_internal_a_actorid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt64ToArray(1, this->_internal_a_actorid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla._ipdltest.PTestDestroyNested.Msg_PTestDestroyNestedSubConstructor)
  return target;
}

size_t Msg_PTestDestroyNestedSubConstructor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla._ipdltest.PTestDestroyNested.Msg_PTestDestroyNestedSubConstructor)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // sint64 a_actorid = 1;
  if (this->_internal_a_actorid() != 0) {
    total_size += ::_pbi::WireFormatLite::SInt64SizePlusOne(this->_internal_a_actorid());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Msg_PTestDestroyNestedSubConstructor::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Msg_PTestDestroyNestedSubConstructor*>(
      &from));
}

void Msg_PTestDestroyNestedSubConstructor::MergeFrom(const Msg_PTestDestroyNestedSubConstructor& from) {
  Msg_PTestDestroyNestedSubConstructor* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla._ipdltest.PTestDestroyNested.Msg_PTestDestroyNestedSubConstructor)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_a_actorid() != 0) {
    _this->_internal_set_a_actorid(from._internal_a_actorid());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Msg_PTestDestroyNestedSubConstructor::CopyFrom(const Msg_PTestDestroyNestedSubConstructor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla._ipdltest.PTestDestroyNested.Msg_PTestDestroyNestedSubConstructor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_PTestDestroyNestedSubConstructor::IsInitialized() const {
  return true;
}

void Msg_PTestDestroyNestedSubConstructor::InternalSwap(Msg_PTestDestroyNestedSubConstructor* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.a_actorid_, other->_impl_.a_actorid_);
}

std::string Msg_PTestDestroyNestedSubConstructor::GetTypeName() const {
  return "protobuf.mozilla._ipdltest.PTestDestroyNested.Msg_PTestDestroyNestedSubConstructor";
}


// ===================================================================

class Reply_PTestDestroyNestedSubConstructor::_Internal {
 public:
};

Reply_PTestDestroyNestedSubConstructor::Reply_PTestDestroyNestedSubConstructor(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf.mozilla._ipdltest.PTestDestroyNested.Reply_PTestDestroyNestedSubConstructor)
}
Reply_PTestDestroyNestedSubConstructor::Reply_PTestDestroyNestedSubConstructor(const Reply_PTestDestroyNestedSubConstructor& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  Reply_PTestDestroyNestedSubConstructor* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protobuf.mozilla._ipdltest.PTestDestroyNested.Reply_PTestDestroyNestedSubConstructor)
}

inline void Reply_PTestDestroyNestedSubConstructor::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_._cached_size_)*/{}
  };
}

Reply_PTestDestroyNestedSubConstructor::~Reply_PTestDestroyNestedSubConstructor() {
  // @@protoc_insertion_point(destructor:protobuf.mozilla._ipdltest.PTestDestroyNested.Reply_PTestDestroyNestedSubConstructor)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Reply_PTestDestroyNestedSubConstructor::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Reply_PTestDestroyNestedSubConstructor::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Reply_PTestDestroyNestedSubConstructor::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.mozilla._ipdltest.PTestDestroyNested.Reply_PTestDestroyNestedSubConstructor)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear<std::string>();
}

const char* Reply_PTestDestroyNestedSubConstructor::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Reply_PTestDestroyNestedSubConstructor::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.mozilla._ipdltest.PTestDestroyNested.Reply_PTestDestroyNestedSubConstructor)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.mozilla._ipdltest.PTestDestroyNested.Reply_PTestDestroyNestedSubConstructor)
  return target;
}

size_t Reply_PTestDestroyNestedSubConstructor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.mozilla._ipdltest.PTestDestroyNested.Reply_PTestDestroyNestedSubConstructor)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Reply_PTestDestroyNestedSubConstructor::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const Reply_PTestDestroyNestedSubConstructor*>(
      &from));
}

void Reply_PTestDestroyNestedSubConstructor::MergeFrom(const Reply_PTestDestroyNestedSubConstructor& from) {
  Reply_PTestDestroyNestedSubConstructor* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.mozilla._ipdltest.PTestDestroyNested.Reply_PTestDestroyNestedSubConstructor)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void Reply_PTestDestroyNestedSubConstructor::CopyFrom(const Reply_PTestDestroyNestedSubConstructor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.mozilla._ipdltest.PTestDestroyNested.Reply_PTestDestroyNestedSubConstructor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Reply_PTestDestroyNestedSubConstructor::IsInitialized() const {
  return true;
}

void Reply_PTestDestroyNestedSubConstructor::InternalSwap(Reply_PTestDestroyNestedSubConstructor* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
}

std::string Reply_PTestDestroyNestedSubConstructor::GetTypeName() const {
  return "protobuf.mozilla._ipdltest.PTestDestroyNested.Reply_PTestDestroyNestedSubConstructor";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace PTestDestroyNested
}  // namespace _ipdltest
}  // namespace mozilla
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::_ipdltest::PTestDestroyNested::Msg_PTestDestroyNestedSubConstructor*
Arena::CreateMaybeMessage< ::protobuf::mozilla::_ipdltest::PTestDestroyNested::Msg_PTestDestroyNestedSubConstructor >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::_ipdltest::PTestDestroyNested::Msg_PTestDestroyNestedSubConstructor >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf::mozilla::_ipdltest::PTestDestroyNested::Reply_PTestDestroyNestedSubConstructor*
Arena::CreateMaybeMessage< ::protobuf::mozilla::_ipdltest::PTestDestroyNested::Reply_PTestDestroyNestedSubConstructor >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::mozilla::_ipdltest::PTestDestroyNested::Reply_PTestDestroyNestedSubConstructor >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
